### ISSUE TITLE
Indico Dashboard: "Happening in your categories" does not show all events

### ISSUE THREAD

**Issue by arescope** [indico/indico#1481]
```yaml
# Ticket imported from Trac
```

From user:

```
Hello Alberto, that would be perfectly fine if it showed me 10 
events sorted in order of increasing date.  But what I get is 
instead only events from a single category extending months into the
future, even though there are events from other categories today 
which are not listed.
```

Think in the ways to make the algorithm

**Comment by arcresu** [comment]
I know that there are many features in the backlog, but this to me seems fairly important since it currently gives the misleading impression that certain events are not happening when in fact they are just missing from the sequence. The ordering should be strictly by date, without omissions, and at the least every event happening today should be visible.

**Comment by pferreir** [comment]
Agreed. It makes sense to come back to this once we have all the categories/events in Postgres.

**Comment by ThiefMaster** [comment]
recently fixed
