### ISSUE TITLE
Create event does not work with Opera Browser

### ISSUE THREAD

**Issue by fmarco76** [indico/indico#1689]
When the button "Create lecture" is pressed in the page for creating a lecture nothing happen.

The same procedure with Google Chrome create the event and move to the page showing the details.

The browser is Opera v. 12.16 for Linux x86_64

**Comment by pferreir** [comment]
Hi,
Can we have some additional data, such as possible errors in the JS console, etc?

**Comment by fmarco76** [comment]
Hi,

actually there is no error in the console when I click the button. It seems like nothing happen.

The browser version is still the same. Let me know if I should do some specific tests.

**Comment by fmarco76** [comment]
At least no error related with the click but only CSS and a JS warning not related with the click

**Comment by pferreir** [comment]
Anyway, Opera 12.16 is quite old, isn't it? Just tried it with 28.0 (OSX) and it works like a charm. Maybe because 12.16 is still Presto?

Anyway, if you can find an actuall JS issue we will be glad to fix it. But otherwise, supporting such an old browser will be counter-productive (same goes for IE8 and other old versions of browsers).
