### ISSUE TITLE
Room Booking: Allow room managers to modify room details

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#1726]
We don't allow room managers to modify details of their rooms. Only admins can do it. The reason for this is to prevent them from modifying important values like the building or IP address of the room.

We could go for an intermediate solution in which room managers can modify _some_ details. How to lock which details can be modified and which can't should be discussed. A couple of approaches for this:
1. The admins can chose which detail entries are locked.
2. A plugin locks some of the detail entries.

**Comment by ThiefMaster** [comment]
I think implementing (2) would be enough since it covers (1) - someone would just need to write a plugin that exposes an interface to lock certain fields. Also, that way we stay more flexible since e.g. our internal FoundationSync plugin can lock fields while others can use a custom plugin to lock fields manually.

Of course the plugin API would have to specify how fields should be locked - for everyone (including admins) or just non-admin room managers.

**Comment by pferreir** [comment]
I'm not that sure about having plugins lock fields. It seems to me like the type of complexity we'd like to avoid.

**Comment by olifre** [comment]
Is this issue still in scope for a 2.2 point release? 
We are requiring a feature like this for distributed room managers (several institutes managing local rooms in a central Indico instance).

**Comment by ThiefMaster** [comment]
It's part of 2.2.3: https://docs.getindico.io/en/stable/changelog/ (which you need to install ASAP for security reasons anyway if you haven't already ;))
