### ISSUE TITLE
Message context (msgctxt) in indico.util.i18n localization

### ISSUE THREAD

**Issue by vokac** [indico/indico#1788]
There are cases where same "msgid" has different translation in different places (e.g. "May" as full name vs. 3 letter shortcut is different in my language). Could you consider to add support for msgctxt in indico.util.i18n (https://www.gnu.org/software/gettext/manual/html_node/Contexts.html) so we can start to mark such ambiguities.

**Comment by pferreir** [comment]
This is a very good point. Thanks for bringing it up!

**Comment by ThiefMaster** [comment]
Unfortunately the jinja extension doesn't seem to support this :/
Would be a nice PR for jinja though... `{% trans 'some_context', foo=bar, foobar=foobar, ... %}` or something like that

**Comment by pferreir** [comment]
Agreed. Once Jinja supports it, we can support it as well. But otherwise our hands are kind of tied (unless we create a Jinja extension for that, which I'd like to avoid).

@vokac , as for "May", can you tell us the places where you're having issues, so that we get rid of the translations and use proper date formatting functions instead? Month names should never need to be translated.

**Comment by vokac** [comment]
@pferrei, I'm using Indico 1.2.0 and that version had month names in several source files. It looks like that was cleaned up and master branch only contain month names in indico/MaKaC/webinterface/wcalendar.py#L263.

**Comment by pferreir** [comment]
@vokac great! And let's get rid of those too...

**Comment by pferreir** [comment]
Done: f09cf7ca215964fe8382a580bfda76ce41993d2c

**Comment by ThiefMaster** [comment]
added in #4870
