### ISSUE TITLE
Remove equipment/attribute nesting

### ISSUE THREAD

**Issue by pferreir** [indico/indico#1799]
Possible in the backend, not through the interface.

**Comment by ThiefMaster** [comment]
Current we don't use nested attributes at all, only equipment. And since we have special handling in the code for certain equipment types (VC children), I believe it would make more sense to refactor this before 2.0...

My suggestion would be to:

- remove nesting - it makes the code (mostly when it comes to non-trivial queries) **a lot** more complicated in various places
- add a flag "is_vc" to equipment types
- use that flag in places where we care about vc-specific equipment
