### ISSUE TITLE
Add "troubleshooting" section to install docs

### ISSUE THREAD

**Issue by pferreir** [indico/indico#1815]
Common problems such as:
 * Permission issues
 * `bcrypt` package issues (trying to compile stuff in run-time)
 * `zc.queue` package permission issues

... and others that show up in the mailing list every now and then.

**Comment by erolg** [comment]
I got 403 Forbidden error, when i follow standart documantation on indico.github.io. I can't access indico-software.org to read old docs. Please update documantations for permission issues in the earliest time.

**Comment by fockeRR** [comment]
Yes, please add information from the mailing list (I can't get archive from the mailing list where I'm logged in). The official installation of Indico 1.2 is buggy!

**Comment by pferreir** [comment]
@erolg, try http://old.indico-software.org
Is there a broken link?

We are slowly migrating stuff to GitHub.

**Comment by pferreir** [comment]
@fockeRR, I'm sure it's buggy, but if you could tell us what are the things that you believe are missing, that would help a lot :wink:

**Comment by danmichaelo** [comment]
Here's one: I got 403 permission denied after a fresh install. It turned out to be because I was using the example configuration from installation.rst with Apache 2.4, where

```
Order deny,allow
Allow from all
```

should be replaced with 

```
Require all granted
```

Perhaps this is worth mentioning directly in [installation.rst](https://github.com/indico/indico/blob/master/doc/dev/source/installation.rst)?

**Comment by pferreir** [comment]
Info on Apache 2.4 config added to docs. Closing issue until further information.
