### ISSUE TITLE
Move `uses_vc` to separate plugin (CERN audiovisual?)

### ISSUE THREAD

**Issue by pferreir** [indico/indico#2071]
This includes all logic that currently depends on this reservation property.
The objective is to make it more configurable and remove the few remaining CERN-specific bits of template data (e.g. [footer in reservation e-mails](https://github.com/indico/indico/blob/master/indico/modules/rb/templates/emails/reservations/creation_email_to_user.txt#L30)).

**Comment by ThiefMaster** [comment]
Some of the videoconference things are tied pretty deep into the RB module (e.g. filtering rooms that support webcast/recording or videoconferencing) while pretending to be dynamic (they check for equipment/attributes). There are a two ways to clean this up:

- if we keep them in the core, let's move them to actual columns (has_vc etc, and an "is_vc" attribute on custom equipment). some checks related to the existence of VC equipment are a huge mess at the moment since we use nested equipment for it (which isn't even supported by the room admin UI)

- remove them from the core and adding them through a plugin (`rb_cern`?). This would require quite a few signals (or more likely template hooks) to add things to the search widget etc. For storing the cern-specific data we could stay with attributes/equipment or switch to a separate table like we did for Vidyo (1:1 relationship with the main room table). Separate table is probably cleaner.

The second one is most likely the better solution, unless we assume that video conferencing is so common that it deserves to be in the core. In that case we could simply use template hooks to move the cern-specific parts e.g. in the emails into a plugin.

**Comment by ThiefMaster** [comment]
Legacy RB feature; replaced with generic room features.
