### ISSUE TITLE
Issues with Arrival and Departure information section in registration section

### ISSUE THREAD

**Issue by mgouzevi** [indico/indico#2175]
Dear Expert,

we are preparing a new event:

https://indico.cern.ch/event/462833/registrations/24283/

The registration form is expected to contain the Arrival and Departure information section. We see it in the edition mode. It seems that nothing is disabled:

https://indico.cern.ch/event/462833/manage/registration/24283/form/

But unfortunately it doesn't appears on the registration form itself:

https://indico.cern.ch/event/462833/registrations/24283/

Could you advice us how to fix that?

best

Maxime && Olivier

**Comment by ThiefMaster** [comment]
Hi, please use indico-support@cern.ch for support questions regarding the CERN Indico instance in the future.

Anyway, the problem is that you created the section as an administrative section, which means it's hidden in the registration form unless you are an event manager (the purpose of administrative sections is to store data only accessible to managers).

The type of a section cannot be changed in the UI, but I can do it for you in the database (that way you won't have to delete the section and recreate all the fields).

**Comment by ThiefMaster** [comment]
I've changed the section type. We are also looking into the error that shows up when trying to view the details of the existing registrations in your event.

**Comment by mgouzevi** [comment]
Thanks much! Would keep in mind about the indico support mail list.

Best
