### ISSUE TITLE
Optionally allow all registrants to access conference pages

### ISSUE THREAD

**Issue by pferreir** [indico/indico#2460]
It makes sense that a user protects an event and configures it in such a way that only registered (and confirmed?) people can access it.

This could be a configurable option, probably in the "protection" page.

**Comment by ThiefMaster** [comment]
Sounds more suitable as an option to sync ACLs with registrations. Adding another source for access rights would be a bit messy IMO (even though it'd be possible with the `acl.can_access` signal)

**Comment by pferreir** [comment]
Just to note yet another user request for this. There have been several lately. I think we have to agree that the list of participants ends up being kind of an ACL. This becomes even more important in very large events.

Synchronization would also be messy. If you have to manually trigger an update every time someone registers, then synchronization loses its purpose.

Maybe the solution would be to add the "participant" role to the ACL, not creating a parallel mechanism?

**Comment by ThiefMaster** [comment]
Maybe using the signal we have would be the best solution, combined with a setting on each registration form whether to grant access to the event for people who are registered (probably also needs a setting whether to require the registration to be 'complete' i.e. paid).

Storing roles with ACL entries sounds awfully like the mess `linkedTo` was - easily gets out of sync etc. (and while ACL out of sync is not such a big deal since it's explicit, having an out of sync list of roles would be quite messy)

**Comment by pferreir** [comment]
> Storing roles with ACL entries sounds awfully like the mess linkedTo

Maybe we're not talking of the same thing? I mean adding "Registrant" as an ACL entry, which would lead Indico to evaluate whether the user is a registrant, in addition to checking group membership and network IP. Would that be messy?

**Comment by ThiefMaster** [comment]
Oh, that makes more sense. I thought you meant roles on the WhateverPrincipal like `submitter` etc

**Comment by pferreir** [comment]
> I thought you meant roles on the WhateverPrincipal like `submitter` etc

No, I really mean adding roles as a 1st class citizens of an ACL. That is something we will probably need anyway (as well as the capability to add new roles) for the conferencing improvements we'll be undertaking next year.

**Comment by nop33** [comment]
> Just to note yet another user request for this. There have been several lately. I think we have to agree that the list of participants ends up being kind of an ACL. This becomes even more important in very large events.

Yet another user requested this:

> The event can be public but the presentations should be available to all of the participants, but not the public. I can add ‘users’ individually but there are over 100 participants and this would take a long time.

**Comment by pferreir** [comment]
Related to #2307

**Comment by bpedersen2** [comment]
I am currently also thinking about this problem (public conference, material only visible for participants).
Some thoughts I have right now: 
 * Implement an EventMemberGroupProxy
    Main problem: Currently the code assumes a group is either a LocalGroup or a MultipassGroup
    This would give automatic updating of registrants
 * Add an option to add registrants to a local group in the registrants list
   Seems not to hard to implement, but needs manual follow-up if done before registration is finalized.

So what is the current status here?

**Comment by ThiefMaster** [comment]
GroupProxy is just for "global" groups - a LocalGroup is not tied to an event but to the whole instance, so it would not be suitable for this.

However, in 2.1 there will be another kind of group that is local to an event (and can be created by event managers, unlike other groups that require admin rights). So far the plan is to only allow adding users to them manually though.

I'm not sure if mixing this with registrants would be a good idea though. Maybe a separate ACL entry type like mentioned in https://github.com/indico/indico/issues/2460#issuecomment-225887722 is better.

**Comment by martingrossmannPSI** [comment]
This question popped up again for one of the conferences I support. Is there any progress? It's more than 3 years ago that Pedro acknowledged this would be a useful feature...

**Comment by pferreir** [comment]
@martingrossmannPSI unfortunately, in a universe of more than 600 issues, it's impossible to ensure everything is tackled in a horizon of months. There are issues that have been open for longer and, as much as we'd love to close them, they remain open because there are others that have higher priority.
I've added the "help wanted" tag to it in November, which means it would be an interesting issue for someone else to pick up and work on, as it's pretty self-contained.

**Comment by ThiefMaster** [comment]
FYI, 2.3 will already allow adding registrants to ACLs: #4477. #4499
Being able to restrict *specific* materials to registered users is currently being worked on: #4505

However, just to be clear, This does *not* include the following things so far:

- being able to restrict the whole event *except for the registration*. If you restrict the event but allow registered people, you will need to register them manually (or only restrict the event after everyone registered, in case there's nothing sensitive in the event before that point)
- being able to restrict all materials without doing it manually on every single material or material folder

**Comment by pferreir** [comment]
I think we need to replace this ticket with one which implements restricting the event save for the registration form. What do you say, @ThiefMaster ?

**Comment by ThiefMaster** [comment]
Yeah... even though I'm not sure how to best do that. I'd really like to avoid having to bring back what we had in 1.x where you had access to a "basic" view of the event as soon as you had access to *something* inside even if you did not have access to the event itself. It just adds a huge amount of complexity because then "can access event" suddenly becomes much less obvious. But I guess we can't really avoid it.

**Comment by pferreir** [comment]
Maybe we should just open up the registration link and that's it? I seriously don't think anything else would really be needed... If people want to present additional information, etc... then they should open up the event or use an access key...

**Comment by ThiefMaster** [comment]
Yeah... so that would be:

- granting access to the registration page(s)
- showing the basic header
- hiding the menu (or all items but registration) in case of a conference
- granting access to custom logo/css since that may be used in the header

Or should we even go a step further and only show the basic registration form like we do with meetings, and disable all customization? So when opening an event that 1) you cannot access and 2) has registrants in the ACL, show a page explaining that the event is only accessible to registered participants, and the link to register (or even go straight to the registration and show the message there).

**Comment by pferreir** [comment]
I would probably go a step further, as you say. I'm not sure we should totally disable customization, though.

**Comment by ThiefMaster** [comment]
I guess there's no harm in keeping css/logo accessible..

**Comment by ThiefMaster** [comment]
closing this in favor of #4528
