### ISSUE TITLE
Add description of the different branches

### ISSUE THREAD

**Issue by danmichaelo** [indico/indico#2565]
Perhaps to DEVELOPMENT.md ? Perhaps also rename DEVELOPMENT.md to CONTRIBUTING.md to make it easier to find on github (https://github.com/blog/1184-contributing-guidelines)

As a new user and potential contributor I'm somewhat confused about the branches. I see that there's a 1.2 range and a 1.9 range, but it's tricky to figure out the differences without scanning through tons and tons of commits (the only release on 1.9 in the release notes is of little help: https://github.com/indico/indico/releases/tag/v1.9.0). I also find it confusing that you jump from 1.2 to 1.9, not 2.0. In the wiki there is mentioning of a 2.0 version, so is that the eventual fate of the 1.9 range?

And then there's both master and devel, but right now there's no difference between them, so what convention do you follow for those, and which should be targeted for PRs?

**Comment by danmichaelo** [comment]
Btw. I found http://indico-software.org/blog/ , which answers some of my questions. But according to that blog, there exists several releases (1.9.8, 1.9.7, etc.) that are not to be found on https://github.com/indico/indico/releases

**Comment by ThiefMaster** [comment]
PRs should be done against master in most cases (i.e. "unless someone told you something else").

The 1.9.x versions are internal releases, hence no public releases on GitHub or PyPI - we use the blog posts to inform people interested in the progress and also to announce those new versions here at CERN (where we use them in production).

1.2.* is the current stable version which we recommend to people for new production setups. It's a bit old and not as pretty as 1.9.x but you'll have an easy upgrade path to 2.0 once it's released (between 1.9.x versions the upgrade is much more tricky and not really documented)

1.9 is 1.9 and not 1.3 exactly because it's much closer to 2.0 (and will eventually become 2.0) than 1.2.

`master` is the latest "stable" development version, i.e. nothing obviously broken. Eventually (after 2.0) most development will go on in there again, but since we are still rewriting major parts we usually use devel to avoid having broken things in `master` (also, we rebase and force-push in `devel` but avoid doing so in `master`).

The reason for `devel` and `master` being in sync right now is that we finished most development on 1.9.8 (we'll actually put it in production next week) and started working on 1.9.9 but since it's still very early it's not merged into `devel` yet (it's in `wip/abstracts` atm).

**Comment by danmichaelo** [comment]
Thanks for clarifying! 1.9.8 *really* looks amazing, so it's very tempting to start using it, our installation will be quite small and with low uptime requirements, but it's still scary if there's no upgrade notes.. Perhaps I should let patience prevail and test 1.2..

Do you have some estimate of when 2.0 will be released or is it impossible to tell ("when it's ready")?

**Comment by ThiefMaster** [comment]
Later this year :) It's really hard to give an exact ETA. We are currently rewriting the abstract and paper reviewing modules which are the last "big" things left. After that it's small things and general cleanup for a nice and clean 2.0 release.

If you want to use 1.9.8 (even though officially we don't recommend it), it'd be best to wait until the end of next week as we release it at CERN next Tuesday and this usually results in most of the bugs we didn't find during our own testing being discovered quickly (the advantage of a large user base ;)), so it'll be more stable at the end of next week.

The upgrade from 1.9.8 to newer versions actually won't be so bad since all the big and ugly steps (moving contributions and everything related to them to the new DB for example) are already done.

**Comment by danmichaelo** [comment]
Cool, thanks, I still have some time to make a decision, but at least now I'm much better suited to do it.
