### ISSUE TITLE
Protection: make it clear why ACL is disabled

### ISSUE THREAD

**Issue by pferreir** [indico/indico#2664]
![image](https://cloud.githubusercontent.com/assets/2699/19648331/0b1f05a6-9a02-11e6-8b8f-69130baaea8f.png)

Some users find it hard to figure out how to enable the ACL when the event is set as public. We could add some kind of indication of the reason why the list is disabled. This could be achieved e.g. with a tooltip.

**Comment by OmeGak** [comment]
Another option is hiding the list unless it's relevant. For discoverability of the feature, instead of hiding the field altogether, we could show a link that would switch the protection mode to protected. It would look like this.

![screenshot from 2016-10-24 15 47 56](https://cloud.githubusercontent.com/assets/716307/19692508/6feecf9e-9ad8-11e6-90ed-ffcb5917a436.png)
