### ISSUE TITLE
Cannot send emails

### ISSUE THREAD

**Issue by positroni** [indico/indico#2671]
Hi again.

I am trying to send notifications with Indico v1.2.1rc11 using a local postfix smtp server that relays to my University smtp server.
I would like to use a fake address that does not exist in my University's database, e.g. "noreply-indico@mydomain.tld".
If I use the mail command as

`echo "indico"  | mail -s Indico -r noreply-indico@mydomain.tld whatever@wherever.com`

it works perfectly. But when Indico sends an email I get an error in postfix that says the email address doesn't exist on the smtp server.
How to configure indico in such a way that I can send email from a non-existent address? 
Now my indico.conf contains

`SmtpServer           = ('localhost', 25)`
`#SmtpLogin            = ""`
`#SmtpPassword         = ""`
`SmtpUseTLS           = "no"`
`SupportEmail         = "root@localhost"`
`PublicSupportEmail   = "root@localhost"`
`NoReplyEmail         = "noreply-indico@mydomain.tld"`

**Comment by ThiefMaster** [comment]
This is not an indico issue but one with your mail server. Since you relay through your university server chances are good that you can only send from your own email address, not from random email addresses.

Indico expects a mail server that accepts emails from the senders it uses (in new code we try to use only the emails configured in the config file to avoid problems with SPF and similar measures); usually this is the case when using a mail server that does not need to use a relay host and also is authorized to send emails for the domain used in your "from" addresses.

**Comment by positroni** [comment]
Using Indico I can send with every existent address that belongs to my University (meaning not mine only, but also the rector's address :) ).

As I said through cli using simply mail command I can use whatever address I want, non-existent or even with a domain not belonging to my university. (e.g. donald@duck.com)

Is there a workaround to make Indico act like the simple "mail" command?

**Comment by ThiefMaster** [comment]
Indico simply uses SMTP. Possibly your local mail server is more restrictive on what it accepts from SMTP connections vs sendmail-style calls (which is what `mail` probably uses).

**Comment by positroni** [comment]
You are right, thanks for the explanation and sorry for the bother!
