### ISSUE TITLE
Date language in Registration page

### ISSUE THREAD

**Issue by boileaum** [indico/indico#2799]
The language change does not apply to date field in the "Registration" page. For example, when French is selected, the date stays in English format. See
<https://indico.math.cnrs.fr/event/1723/registration> for example.

**Comment by pferreir** [comment]
Thanks for the report, but that's expected behaviour, since those fields are custom-named. A solution could be having different (configurable) field names per language, but then it will be up to the manager to do such translation if they feel like...

**Comment by boileaum** [comment]
Sorry but I don't understand how those fields are different from the fields appearing for example on the homepage (See <https://indico.math.cnrs.fr/event/1723/overview>).

**Comment by pferreir** [comment]
Sorry, I clearly misunderstood the issue. I thought you meant actual registration form fields, but now I see what you mean. Those dates have been fixed in the last Indico version (See e.g. https://indico.cern.ch/event/577155/registrations/32336/), even if there are strings in that page that are clearly mistranslated (e.g. "Destinataire"), but that's a dictionary issue.
