### ISSUE TITLE
XSLS exports: export time information in local timezone

### ISSUE THREAD

**Issue by pferreir** [indico/indico#2839]
We currently export most of those things in UTC. We should use the event's local timezone

**Comment by ThiefMaster** [comment]
To discuss when starting to work on it:

We could either simply pass the timezone to the `format_datetime()` calls or we could get rid of them and add support for datetime objects to spreadsheets.py (pass raw datetime objects when generating the data, and add another arg to `generate_xlsx` etc. for the tzinfo to use).

This might allow much nicer handling when exporting to XLSX since it's not a string but actually a date/time then.

**Comment by nop33** [comment]
These are the places where `generate_xlsx` is used:

* abstract export
* contributions export
* registrations export
* sessions export
* surveys export

However, it's only the **contributions export** that makes sense to use the timezone information of the event (since it's the only export that exports information relative to the event timezone - scheduled contributions). The rest of the exports may contain datetime columns, but they are submission_dt, modification_dt, etc.

**Comment by ThiefMaster** [comment]
IMO properly supporting  datetimes makes sense nonetheless, especially since Excel most likely behaves more nicely if it knows something is a datetime.

But within event manager we could always use the event's timezone anyway.
