### ISSUE TITLE
indico_initial_setup  modifies site-packages 

### ISSUE THREAD

**Issue by cederom** [indico/indico#2855]
Hey :-) `indico_initial_setup` script modifies the python's `site-packages` content. That should NEVER happen! Python Modules should be shared among different applications and they should not modify itself. If INDICO wants to store some configuration it should store it inside application/installation configuration path, not the `site-packages`..

**Comment by ThiefMaster** [comment]
Don't worry, we'll clean up the installation process for 2.0. `indico_initial_setup` will not survive that ;)

We'll probably go for an env var to point to the config instead of this makacconfig hack indico currently uses.

**Comment by cederom** [comment]
That would be nice :-) We tried to use INDICO for our telemedical conference in Poland but we used OCS instead.. we did not make INDICO work on our cloud hosting with user level access.

Thank you and Good luck! :-)

**Comment by cederom** [comment]
Please consider user level access setup (no root required at all) and virtualenv to setup multiple INDICO instances. Also some user level wsgi mechanism (like passenger) would be nice..

**Comment by ThiefMaster** [comment]
#2857 fixed all these things. :)

Nothing needs to be done as root and since Indico is just a WSGI application you should probably be able to set it up with no root access at all. FWIW, I built a Python wheel just this friday based on the changes from that PR and got indico running using the dev server on a VM without doing anything as root besides installing some `-devel` libraries needed (e.g. postgresql-devel, python-devel).
