### ISSUE TITLE
Make "Short display URL" visible

### ISSUE THREAD

**Issue by SebastianLopienski** [indico/indico#2889]
Currently, "Short display URL" is hidden - if I visit an event page as a user (not admin), I don't see it. Could it be made more public? Or at least included e.g. in HTML meta tags?

**Comment by ThiefMaster** [comment]
What would be the advantage of this? The shortcut URL is mostly for managers to put it on posters etc - when you are already in Indico you usually don't really need it. Including it as the canonical URL in the meta tags is problematic since the short URL can be changed, which would then break search engine links using that URL instead of the one with the ID.

**Comment by SebastianLopienski** [comment]
My use case is that of the event organizer. When I'm browsing my event, and need to get its short URL, I have to go to the "manage" part... (I agree, it's not a strong requirement)

BTW, why would putting the URL in a meta tag with arbitrary name (e.g. "Indico short URL") affect search engines? I didn't mean the canonical URL.

**Comment by ThiefMaster** [comment]
Fair enough. FWIW, In 1.9.10 (check on indico-staging, general event settings style v1 or v2) there's a quick way to copy the shortcut URL with a single click from the management area.

No, an arbitrary tag would work but except for scraping HTML (which is bad - that's what the API is for even though I'm not sure whether we include the shorturl there) I don't see its value.

**Comment by SebastianLopienski** [comment]
A quick way to copy the shortcut URL will indeed be very welcome! Right now, I need to select it with a mouse (as double-click selects "edit" link too...). 

OK, feel free to close this ticket.
