### ISSUE TITLE
Add missing tag v1.9.10 on GitHub

### ISSUE THREAD

**Issue by omasanori** [indico/indico#2957]
While the version of master branch is 1.9.11.dev3 now, there is no `v1.9.10` tag. Would you provide the tag on GitHub if it is available on a developer's local repository but forgot to do `git push --tags`?

I'm sorry if 1.9.10 has been skipped for any reason.

**Comment by ThiefMaster** [comment]
Since 1.9.x versions aren't official releases we only create tags for them, once a version is dead/frozen. 1.9.10 is the version we use at CERN so we do bugfixes there, which is why we keep it as a branch instead of a tag.

Once we move to 1.9.11 (or more likely 2.0), the v1.9.10 branch will be replaced with a tag though.

---

After 2.0 we will of course create tags for every released version.

**Comment by omasanori** [comment]
I see. Thank you for your explanation!
