### ISSUE TITLE
Short/nice link - make it work for subpages too

### ISSUE THREAD

**Issue by SebastianLopienski** [indico/indico#2973]
For example, these two URLs point to the same event:
* `https://indico.cern.ch/event/591480`
* `https://indico.cern.ch/event/tCSC-2017`

Consequently, I'd assume that both these links work:
* `https://indico.cern.ch/event/591480/registrations`
* `https://indico.cern.ch/event/tCSC-2017/registrations` 
... but only the first one works, and the second says _"Page not found"_

**Comment by ThiefMaster** [comment]
The fact that shorturls work at all in `/event/` is mainly due to legacy having used them without the `/e/` prefix for some time. Nowadays they are only displayed in `/e/` urls and since they may contain slashes (only works in `/e/` but not in `/event/`) supporting shorturls somewhere else would make things rather awful since now we would have to handle dealing with 404s and possible collisions with "normal" URLs.

**Comment by SebastianLopienski** [comment]
Pity that this (IMO intuitive) functionality cannot be implemented :-( Allowing slashes in short urls was probably not a good design decision (again, IMHO). But I understand it's hard to change it now... Anyway, thanks for having considered it.

**Comment by ThiefMaster** [comment]
It was already like this in legacy, and while I usually dislike slashes in URL segments too, they are not so bad for shortcuts, e.g. in case of event collections ('CSC/2017', 'ASDF/1234', etc)
