### ISSUE TITLE
Define the HTML tag policy for titles, descriptions, minutes...

### ISSUE THREAD

**Issue by pferreir** [indico/indico#3]
``` yaml
# Ticket imported from Trac
```

The policy regarding HTML should be defined, for different cases:
- Titles - Currently allowed, but will sometimes break the markup (not to speak of the effect it has on metadata). Since we currently allow CSS customization, maybe we could just get rid of it for good;
- Descriptions - Mixed feelings here - a limited set of HTML would be OK. Once again, CSS customization should compensate for this;
- Minutes - Should not have more freedom than descriptions or titles - inline minutes can break the layout;

HTML is no easy to cope with. We could either:
- use some other format (WikiMarkup?) and then convert it to HTML in render time. We would then have the full control over the "safety" of the HTML;
- remove/reject all the HTML except for tags inside a "whitelist";

Number 2 seems to be the most feasible right now.

**Comment by OmeGak** [comment]
Some very valid points coming from an error report regarding the **Evaluation Form** but that can probably apply to many other places in Indico:

* One never knows where HTML is enabled or not so one can only find out by trial and error.
* Sometimes some tags are allowed and some not.
* Sometimes, forbidden HTML is validated and then the page is broken to the point the user has no way to modify it if not removing the element (a question in the evaluation form, in this case) completely.

Also, it seems we are missing escaping some quotation marks.

```html
foo <span style="font-weight:bold">bar</span>
```

Produces:

```html
<input type="text" value="foo span style="font-weight:bold">bar</span>">
```

The easy workaround is to use single quotation marks ' instead of " for HTML attributes. Sometimes even that does not work, than just leaving the quotation marks does the job
