### ISSUE TITLE
Editable book of abstracts

### ISSUE THREAD

**Issue by meluru** [indico/indico#3039]
The idea is to let event managers export the book of abstracts in LaTeX format, so they can edit it in a preferable way. 

It was also suggested by the user that Indico could provide some basic settings to edit the book of abstract (add title page, programme, organising committee, be able to edit abstract page) and have an overview of how the exported book of abstracts will look.

When uploading the file we could use the new `File` model (same one we use for files in the editing module) and just store the ID of that file in the `boa_settings` SettingsProxy. Alternatively, we could add a new `custom_boa_file_id` FK column referencing a File to the `Event` model.

**Comment by ThiefMaster** [comment]
> and have an overview of how the exported book of abstracts will look.

Except creating one with dummy data (like we do in the notification email preview) I don't see any good way to do so.

**Comment by pferreir** [comment]
We should also have an "upload custom BoA" option,  which serves an uploaded PDF instead of the default generated one.

**Comment by bpedersen2** [comment]
Downloading should be possible if #3434 get's accepted

**Comment by bpedersen2** [comment]
As for the custom BoA: We do this by:
1. disable the standard BoA link
2. Upload the file as material (the hidden folder option is useful here)
3. Link this via a custom page pointing to the url

**Comment by giordand** [comment]
will it be in Release 2.2?

**Comment by ThiefMaster** [comment]
@giordand Unfortunately not, but we'll try to get at least the import/export part in 2.3.

**Comment by joshuabarrow221** [comment]
Hello,
I have used the "Book of Abstracts" feature on a Fermi National Accelerator Laboratory (FNAL) server to collect contributions from our participants. I cannot find the seemingly newly added feature to output a LaTeX document directly instead of only a PDF. If I advocate that FNAL update to the newly merged build (I see this seems to have happened two weeks ago), will I be able to do so?

**Comment by ThiefMaster** [comment]
@joshuabarrow221 

Hi, version 2.3 is only deployed on indico.cern.ch at the moment. While anyone could in principle build an indico page based on master (2.3-dev), we do not recommend this since we just deployed a few days ago and still find some (minor) bugs. So we recommend waiting with the upgrade a bit longer until we made a "real" 2.3 release.

**Comment by joshuabarrow221** [comment]
Thanks; I'll keep an eye out for that.
