### ISSUE TITLE
Documentation for Indico users & event administrators?

### ISSUE THREAD

**Issue by pcolmer** [indico/indico#3059]
I'm very interested in what Indico can do but, I'll be honest, I am struggling with figuring out how to get an event fully defined within it.

I'm getting lost between what is a "Session" and what is a "Session block".

I don't understand how an attendee who has registered for the event can select sessions from the timetable in order to build a personal schedule.

The YouTube video talks about an ecosystem of add-ons but I cannot find any further reference to them.

Thanks :)

**Comment by ThiefMaster** [comment]
We have some user documentation here which will also be linked from within Indico in 2.0: https://learn.getindico.io/

> I'm getting lost between what is a "Session" and what is a "Session block"
A session block is a part of a session in the timetable. A session might take place on more than one day, but since each timetable entry can only be on a single day you create blocks for every "block" of the session you want in the timetable.

> I don't understand how an attendee who has registered for the event can select sessions from the timetable in order to build a personal schedule.
There is no such feature in Indico. However, we might add a "favorite" feature in the future (for both events and items within events).

> The YouTube video talks about an ecosystem of add-ons
https://github.com/indico/indico-plugins - with 2.0 we will put these plugins on PyPI so they can be installed as easily as Indico itself.

**Comment by pcolmer** [comment]
Thank you for your reply.
