### ISSUE TITLE
Changing indico root directory

### ISSUE THREAD

**Issue by sdspacecowboy** [indico/indico#3098]
By default indico is saved in /opt/indico

How does one save it in something like /var/www/html/ ?

**Comment by ThiefMaster** [comment]
`/var/www/html` sound a lot like the document root of your webserver (i.e. the directory that's served when you access `https://yourdomain.com`). If that's the case, you should **not install indico there under any circumstances**.

Anyway, you can follow the installation guide and use any path instead of `/opt/indico`; just make sure to adapt all the steps accordingly.

Also, keep in mind you are more or less on your own when using a non-standard setup - we tested `/opt/indico` but it should work in other locations. Just make sure that nothing is inside your webserver's document root to avoid leaking sensitive data (such as your config file containing the database password or uploaded files)

**Comment by sdspacecowboy** [comment]
My sys admin has the network file system is set up on /var/www/

Just figuring out how to get indico to be served from it. I assumed that it could be put into /html/ but that's an no go if there are security concerns like you said. It should be fine in /var/www/ ?

**Comment by ThiefMaster** [comment]
Not sure I understand you correctly - if with network file system you mean something like NFS: There's usually no good reason to store any of the indico files on NFS (except for the `archive` folder if you use more than one worker machine serving indico).

If you just mean the default directory where web stuff is stored: You can easily run other websites on the same server (if you really want to do that - especially if you can use VMs it's probably better to keep one VM per application) from different locations, e.g. the other sites from `/var/www` and indico from `/opt/indico`.

Anyway, like I said, just make sure none of the indico files are accessible via HTTP (except e.g. static assets etc. that are explicitly exposed via aliases). `/var/www/indico` instead of `/opt/indico` would probably be fine, if there is no document root pointing to `/var/www` in any of your webserver's config files.
