### ISSUE TITLE
Override macros

### ISSUE THREAD

**Issue by knusperman** [indico/indico#3131]
Hey,

assume I want to customize timeline.html for paper reviewing. I create my customized file at the right location and it is loaded, but due to http://jinja.pocoo.org/docs/dev/faq/#my-macros-are-overridden-by-something (and related to it https://stackoverflow.com/questions/26582731/redefining-imported-jinja-macros) the overwriting of macros needs an extra wrapper around the parent file. 

Wouldn't it be handy to add these wrappers around all macros or did I miss something?

In parent file: 
`{% if not render_paper_review_action_text %}
{% macro render_paper_review_action_text(review) %}
    ...
{% endmacro %}
{% endif %}`

In customized file:

`{%extends '~events/papers/reviewing/timeline.html' %}
{% macro render_paper_review_action_text(review) %}
...
{% endmacro %}
`

Best,
Markus

**Comment by ThiefMaster** [comment]
I think this would add quite some overhead (mostly regarding readability of the templates).

What are you trying to customize there (unless this is just an example)? Overriding whole macros seems like a VERY easy way to end up with customizations that need to be adapted after updates and should be avoided. There might even be a better way to do what you are trying to do (one that does not involve overriding macros).

**Comment by knusperman** [comment]
I'm trying to get the whole reviewing process anonymised. Right now content reviewers can see the names of the name of the submitter in the timeline. For this I need to change `render_submission_info` for instance. What would you suggest in this case?

**Comment by ThiefMaster** [comment]
I think this is way outside the scope of customizations or even plugins. I would rather implement something like this in the Indico core - adding a setting when setting up reviewing would be quite easy, and so would be checking it when showing the timeline. Of course it would make sense to contribute this back using a pull request to avoid having to maintain a customized Indico core.

BTW, don't papers usually contain the name of the authors in the paper itself? So anonymizing the UI seems a bit like a moot point. Also, keep in mind that paper reviewing takes place for existing contributions of the event - usually the list of contributions is public, or at least the timetable from which the contribution details are linked. So a reviewer could always go to the contribution list and check whose contribution it is.

If that is not a problem for you (e.g. because you just don't want them to see the name immediately when viewing the paper), you might go for the very dirty way of hiding elements via CSS (in the end it doesn't make a big difference whether someone uses "view source" or uses the contribution list).

**Comment by knusperman** [comment]
Actually, we first implemented it as you described it. The new setting in the call for paper module checked and with respect to it the frontend was adjusted. My idea was to avoid this customization of core by using template customization... but I guess you are right ;)

You will hear from us regarding a pull request. 

Regarding your note: Yes, we know about the list of contributions. Our idea is to use the call for abstract module and then immediately push the abstract to the call for paper module (i.e. auto-accepting the abstract via plugin), so that it becomes a contribution directly after submission. The contribution list will be published after judgment.

**Comment by ThiefMaster** [comment]
Obsolete since we moved the timeline to react since then.
