### ISSUE TITLE
Include configuration for logrotate in installation docs

### ISSUE THREAD

**Issue by driehle** [indico/indico#3244]
I suggest that a configuration for logrotate should be included in the installation docs.

The following works for Debian 8 onwards:
```bash
cat > /etc/logrotate.d/indico <<'EOF'
/opt/indico/log/indico.log
/opt/indico/log/celery.log
/opt/indico/log/other.log
{
        daily
        missingok
        rotate 14
        compress
        delaycompress
        notifempty
        sharedscripts
        postrotate
                if /bin/systemctl status uwsgi > /dev/null ; then \
                    /bin/systemctl reload uwsgi > /dev/null; \
                fi; \
                if /bin/systemctl status indico-celery ; then \
                    /bin/systemctl restart indico-celery > /dev/null; \
                fi;
        endscript
}
EOF
```

**Comment by ThiefMaster** [comment]
Logrotate is indeed useful, but in most smaller setups the logs would take rather long to become big enough to make rotating important. It's something a server admin should indeed setup though when necessary.

There is http://uwsgi-docs.readthedocs.io/en/latest/Options.html#touch-logreopen btw, which would usually be better than reloading uWSGI (which reloads the Python app and causes a few moments of slowness or downtime). But IIRC. it wasn't completely reliable for us so we also switched to a systemd reload. It happens at night anyway so the impact is limited (never had a user complain)

PS: I don't think the postrotate script needs to be a single statement, so all those backslashes can probably go away. Also, you can use `try-restart` instead of `restart` and and thus skip the status check (`try-reload` might exist as well).

---

This is the logrotate script we are using btw:

```logrotate
/opt/indico/log/indico.log /opt/indico/log/celery.log /opt/indico/log/other.log {
        compress
        create 0644 indico indico
        daily
        dateext
        delaycompress
        missingok
        notifempty
        olddir old
        rotate 31
        sharedscripts

        postrotate
        systemctl reload uwsgi || true
        systemctl try-restart indico-celery || true
        endscript
}
```

For a smaller instance I would probably use `weekly` and tune the `rotate` number depending on how long you want to keep logs.
