### ISSUE TITLE
Cant trace post request(for captcha)

### ISSUE THREAD

**Issue by Ovmedia** [indico/indico#3261]
hello indico 

İ want to add captcha on registration form but cant trace post request. I want to find request, cause of need to check captcha token, i search all day where the request but its so complicated. I can accept all your advices and if somebody help me with that, im so appriciate that

Thanks

**Comment by bpedersen2** [comment]
You probably should implement a new field type and add this to the list in indico/modules/events/registration/fields/__init__.py 
The field implementation then should do the correct validation in it's _validators properties. See e.g. fields/simple.py.

 A signal hook to inject more field types from plugins at this point would probably be an idea.

**Comment by ThiefMaster** [comment]
Which registration do you mean? Creating an indico account (you probably don't need a captcha there unless you have bots that use valid emails and then continue the registration after validating their email address) or registering for an event?

---

> A signal hook to inject more field types from plugins at this point would probably be an idea.

Currently this is tricky since the field types are not extensible, mainly due to the fact that there is a huge mess of old AngularJS code on the client side related to regform fields.

But I don't think using a regform field would be a good idea here - it's not information you want to keep anyway. I think it'd be better to just add a setting whether to require a captcha or not on the registration form level, and then show one below (before the submit button). The class where a registration is being submitted (when performed by a regular user) is `RHRegistrationForm`. You probably want to show the captcha only when the user is not logged in, as logged-in users are generally known to be real (they have at least a validated email address).

Regarding the choice of captcha, the latest reCaptcha is probably the best option, as it is the least annoying one for users.

**Comment by Ovmedia** [comment]
i want to put captcha on registering for an event
> You probably want to show the captcha only when the user is not logged 

Yeah its true, i think when users can register on event this can be exploitable, That's why i want to put captcha

> the latest reCaptcha is probably the best option

I agree with you  and i try to focus this class RHRegistrationForm

>You probably should implement a new field type and add this to the list in indico/modules/events/registration/fields/__init__.py

i will investigate this python file

Thanks for helping

**Comment by ThiefMaster** [comment]
You probably don't need to touch `fields/__init__.py` for the reason mentioned in my previous comments ;)

> Yeah its true, i think when users can register on event this can be exploitable, That's why i want to put captcha

Just as a heads-up, depending on your users you could just require everyone who registers to have an account. In any case, here at CERN we never had any spam issues even with open registrations. Maybe because of the AngularJS mess resulting in spam bots not see any of the form fields. So unless you have an issue with spam registrations I would reconsider spending the time to implement a captcha.

**Comment by ThiefMaster** [comment]
Discussions like this are better placed in our [forum](https://talk.getindico.io/). Feel free to post there if you have more questions.
