### ISSUE TITLE
"Check it out here"

### ISSUE THREAD

**Issue by eveferon** [indico/indico#3355]
In the registration summary, the standard text to refer to the check out section of the registration summary is called "**check it out** here". We were asked to replace it by something less informal like "See below". Would that be a reasonable change? 

[Screenshot](http://funkyimg.com/i/2GmWy.png)

**Comment by eveferon** [comment]
Shall we do it or will you include it into the next patch?

**Comment by ThiefMaster** [comment]
Since it's a one-line change I think it's easier if we just change it (and include it in 2.1) without waiting for a Pull request.

If you need it before 2.1 is released (very soon), feel free to simply edit the template file. When using the default installation path, it is:

    /opt/indico/.venv/lib/python2.7/site-packages/indico/modules/events/registration/templates/display/registration_summary.html

Of course your edit will be lost when updating Indico, but the next release will be 2.1 anyway, and the new text will be there.
