### ISSUE TITLE
Abstract reviewing: Implement "track judges"

### ISSUE THREAD

**Issue by pferreir** [indico/indico#3430]
Currently, the responsibility of judging abstracts is delegated on the event managers. The idea would be to have a "judge" role as it is already the case with Paper Reviewing.
We should make sure that ongoing events are not disrupted due to loss of privileges owing to this.

**Comment by bpedersen2** [comment]
There is the option :Allow track conveners to judge, 
but I agree that the displayed convener may not be the one doing the real work.

**Comment by pferreir** [comment]
I will close this since we have already got the convener role and the "allow track conveners to judge" option.

**Comment by ferdymercury** [comment]
I have a related question, I am a 'track convener', but also an 'event manager'. As track convener, I am apparently allowed to judge:
![image](https://user-images.githubusercontent.com/10653970/100515547-fa343b00-314a-11eb-9cf2-ab8a07518f96.png)

![image](https://user-images.githubusercontent.com/10653970/100515562-146e1900-314b-11eb-9ac5-02435ec70f38.png)

even if the setting is:
![image](https://user-images.githubusercontent.com/10653970/100515581-2fd92400-314b-11eb-86d6-1e9fe82f92d4.png)

Isn't this contradictory? Or is it because I am also an 'event manager'? Maybe this could be clarified in the footnote when assigning roles? Thanks.

**Comment by ThiefMaster** [comment]
As an event manager you have full powers at any time, so you can judge regardless of assignments and configuration.
