### ISSUE TITLE
Expose booking_limit_days validation on client-side

### ISSUE THREAD

**Issue by mvidalgarcia** [indico/indico#3567]
Whenever the limit is being surpassed...
Ideas:
1. Hiding the room at all from search results
2. Showing a warning icon directly in the results with a explanatory tooltip.
3. Showing a warning/error in the booking dialog with a explanation and disabling the booking button.

I'm mostly inclined to the 2nd + 3rd.

**Comment by pferreir** [comment]
Implementation strategy [here](https://github.com/indico/indico/issues/3630#issuecomment-457275174).

**Comment by pferreir** [comment]
Idea from @ThiefMaster: add such rooms as "plan B" option where the length is shortened.

**Comment by pferreir** [comment]
Just discussed the implementation with @panagiotappl and a possible approach would be:
 * Change backend search query so that it doesn't return rooms that have a booking_limit that exceeds the length of the booking;
 * Change plan B endpoint so that it returns such rooms in addition to the currently returned ones;
