### ISSUE TITLE
ur'strings' are syntax errors in Python 3

### ISSUE THREAD

**Issue by cclauss** [indico/indico#3838]
In Python 3, you can have __u'strings'__ or __r'strings'__ but __ur'string' is a ___syntax error___.

$ __python3 -c "ur'string'"__  # --> syntax error

[flake8](http://flake8.pycqa.org) testing of https://github.com/indico/indico on Python 3.7.1

$ __flake8 . --count --select=E9,F63,F72,F822 --show-source --statistics__
```
./indico/legacy/pdfinterface/conference.py:148:56: E999 SyntaxError: invalid syntax
            if i > 0 and re.match(ur'<(p|ul|ol)\b[^>]*>', part):
                                                       ^
./indico/web/http_api/metadata/xml.py:47:90: E999 SyntaxError: invalid syntax
    def _convert(self, value, _control_char_re=re.compile(ur'[\x00-\x08\x0b\x0c\x0e-\x1f]')):
                                                                                         ^
./indico/modules/rb/models/rooms_test.py:470:16: E999 SyntaxError: invalid syntax
    (ur'foo\bar', ur'foo\bar', ''),
               ^
./indico/util/string.py:164:31: E999 SyntaxError: invalid syntax
    value = re.sub(ur'[^\w\s-]', u'', value).strip()
                              ^
./indico/util/spreadsheets.py:55:65: E999 SyntaxError: invalid syntax
def _prepare_csv_data(data, _linebreak_re=re.compile(ur'(\r?\n)+')):
                                                                ^
./indico/util/console.py:114:77: E999 SyntaxError: invalid syntax
    string = re.sub(ur'%\{(?P<fg>[a-z]+)(?P<fg_bold>!?)(?:,(?P<bg>[a-z]+))?}', _cformat_sub, string)
                                                                            ^
./indico/util/mdx_latex.py:627:52: E999 SyntaxError: invalid syntax
        new_blocks = [re.sub(ur'<a[^>]*>([^<]+)</a>', lambda m: convert_link_to_latex(m.group(0)).strip(), block)
                                                   ^
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. These 5 are different from most other flake8 issues which are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

**Comment by ThiefMaster** [comment]
We'll fix that when we switch to Python 3 since AFAIK there is no workaround for this that keeps the same behavior in Python 2 and Python 3.

Please do not open separate issues about things that need to be done when switching to Python 3, especially not if they are obvious once running on Python 3 (by being syntax errors).

**Comment by rooterkyberian** [comment]
After migrating couple projects to Python 3 I have to say its best to do the migration gradually, even if its at the cost of supporting (not necessary officially) both of Python 2 and 3 at the same time. That way the amount of work required to do the final switch is minimized instead of just having a growing TODO list.

In this case `from __future__ import unicode_literals` + removal of `u` prefix should fix all of these, keeping the same behavior in Python 2 and Python 3, of course it will affect other strings as well.
As for less radical fixes, in most cases (if not all?) replacing things like `ur'[^\w\s-]' with `br'[^\w\s-]'.decode()`  will reproduce exactly the same thing. 

I will try to create a PR for this.

**Comment by cclauss** [comment]
Nice.  I concur on your advise to make "small moves" and keep merging them back into master instead of keeping lots of changes on a separate branch.  The continuous feedback is important and the "big bang" migrations usually fail badly.  Nice tips on __unicode_literals__.  Thx.
