### ISSUE TITLE
Room Booking: being able to search by "booked for"

### ISSUE THREAD

**Issue by pferreir** [indico/indico#3959]
It's currently not possible to search for a booking using its owner's name (search field in filter bar).
This is needed especially for Burotel but is of general interest.

**Comment by ThiefMaster** [comment]
Most likely needs to be a separate filter (NOT the normal freetext one) because the text filter only affects the room list, but the booked-for filter will affect the list of reservations.

We could actually show the user search dialog instead of freetext for the new one since we always have a user associated now.

**Comment by pferreir** [comment]
> We could actually show the user search dialog instead of freetext for the new one since we always have a user associated now

But it looks a bit cumbersome that we have to look for a person first. I would keep it as free text.

**Comment by ThiefMaster** [comment]
Does it? At least with a very common name it seems easier to choose the user (likely among your favorites) instead ending up with bookings for others with the same name.

Also, it would allow us to add just a simple button to choose the user instead of another text field (the horizontal space is already very limited, and adding another field will result in wrapping the bar even on 1440p)
