### ISSUE TITLE
Cannot open "Material Editor'" or any other edit-like feature on Mozilla Firefox

### ISSUE THREAD

**Issue by Cristian-Baldenegro** [indico/indico#4002]
Cannot open "Material Editor'' on the event Timetable, or any other edit-like feature, on Mozilla Firefox.

This had not been a problem for me on the last couple of years, but in the last week or so I have not been able to use any of the Edit options on Indico as page manager.

Thanks a lot,
Cristian

**Comment by ThiefMaster** [comment]
Which Firefox version are you using, and are there any errors in the console (F12 to open)?

**Comment by Cristian-Baldenegro** [comment]
Mozilla Firefox 49.0.2

Yes, I am using indico.cern.ch (apologies for not specifying this before).

This is a printout of the errors in the console I get when I try to open an event ``Timetable'', (w/ F12):

SyntaxError: missing = in const declarationcommon.6670b350.bundle.js:12:3140
ReferenceError: $T is not defined
[Learn More]main.2c81ef4f.bundle.js:1:999
ReferenceError: moment is not defined
[Learn More]timetable:65:13
ReferenceError: exportPopups is not defined
[Learn More]timetable:492:9
ReferenceError: $ is not defined
[Learn More]timetable:673:5
ReferenceError: $ is not defined
[Learn More]timetable:849:9
ReferenceError: $ is not defined
[Learn More]

**Comment by ThiefMaster** [comment]
You need to update. That browser is three years old (and not even ESR - but even ESRs that old are end-of-life by now). That means you are surfing with a browser that is not only very outdated but also has **known security issues**.

Anyway, it's not supported anymore since 2.2. We'll fix the "your browser is outdated" message to actually show up in such old Firefox versions as well (not only in IE) soon: #4007
