### ISSUE TITLE
Room booking: booking from event creation doesn't work in some categories

### ISSUE THREAD

**Issue by jouvin** [indico/indico#4075]
I have one category (and it seems only this one) in which room booking is not proposed (or conflict mentioned) during an event creation with a room managed by Indico selected. I don't find what can be specific with this category, apart from its name "Bac à sable" (sandbox). I tested at CERN Indico and found it was perfectly working in the "Test" category (which has the same purpose).

Any idea of what could be wrong?

**Comment by ThiefMaster** [comment]
Did you exclude it in the RB admin settings?

**Comment by jouvin** [comment]
No. "Disable booking during event creation" field is empty, I double-checked before filling the issue... and after your message!

**Comment by jouvin** [comment]
I checked this problem after 2.3 upgrade and the problem is still there. Any idea on how to troubleshoot this?

**Comment by ThiefMaster** [comment]
Is there any place where we can test it (e.g. a test account on your instance)? Otherwise trying to find out in which case this doesn't work is a wild goose chase..

Also, can you check in the browser's dev tools whether a request is sent to `.../api/rooms/.../availability/simple` once you select a room from the dropdown (if yes, the JSON response for that request would be helpful to see)? Or are there any errors in the console?

**Comment by ThiefMaster** [comment]
This happens because the category is set to UTC while the server itself is set to Europe/Paris.

Since it makes little sense to book a (physical) room if the event does not even take place in the same timezone, and room booking is timezone-agnostic (bookings are supposed to be in the timezone where the room is physically located, but Indico does not know what timezone that is), we simply don't show room booking functionality.

(yes, this assumes that all rooms are in the default timezone of the instance, but this is usually the case)

**Comment by jouvin** [comment]
Thanks! I guess it is documented and that I missed it...

**Comment by ThiefMaster** [comment]
I don't think so (tbh i don't know where we'd best put that) :/

**Comment by jouvin** [comment]
I don't have a strong opinion but probably some sort of FAQ to help troubleshooting such a trivial misconfiguration...
