### ISSUE TITLE
Room booking: room defined in an event should be matched exactly

### ISSUE THREAD

**Issue by jouvin** [indico/indico#4089]
We have 2 rooms: `200/1-166` and `200/1-166g`. If I create an event, define that I want to use `200/1-166` without booking the room during event creation, when I book the room from the event settings, the room name is using a partial match against the list of room names and both rooms are proposed instead of only the one defined in the event settings. IMO, it is unexpected.

**Comment by ThiefMaster** [comment]
Good point, showing only an exact match would indeed be a good idea. I wonder what'd be the best way to implement this.. in other places we use `#id` in the search field to select a room solely based on its ID, so that'd be an option. Another option would be putting it in quotes, and doing an exact match in that case.

If there are rooms that only differ in their verbose name and not in the building/floor/room numbering, the latter won't work well (unless we used the full name to match + prefill).

**Comment by ThiefMaster** [comment]
I noticed that we already support the `#id` filtering there, so that might be the easiest option. The only disadvantage is that it doesn't look super amazing, but we already do the same when going from room details to calendar view, so I'd say this is acceptable (in the future we could see about showing something nicer there if the text field was prefilled with a room id).
