### ISSUE TITLE
Room booking: monthly view as the booking calendar default view

### ISSUE THREAD

**Issue by jouvin** [indico/indico#4091]
Currently the `Bookings` menu shows by default a daily calendar view with the ability to change it to a weekly or monthly view. Especially for new users, it is very confusing because the people miss the view-related buttons and are surprised not to see their reservations. The monthly view would probably be a better default and would be more consistent with what you get from room details when clicking on "See all bookings".

**Comment by pferreir** [comment]
We don't have that experience here at CERN, as no one so far has pointed that out. Even in the usability tests that we conducted with real users, that didn't come up at all.
It would also be very heavy for the application to load 1 month worth of reservations for all rooms and render them (not to mention that the month view is not the most "readable" of all).

That said, if in your case you find that's a better default (maybe because you have fewer rooms or are used to reserve rooms for longer periods), you can always customize your instance to do so. Have a look at the [burotel code](https://github.com/indico/indico-plugins-cern/tree/master/burotel) and you'll see how we're using component overrides to change the default behaviour of the application.

**Comment by jouvin** [comment]
Thanks!
