### ISSUE TITLE
Registration Form: hide it if not scheduled and not open

### ISSUE THREAD

**Issue by pferreir** [indico/indico#4122]
Right now we always show all registration forms on the display page of an event. Those which are closed are shown as disabled.
I suggest we just hide any forms which are not available. The exception would be scheduled forms whose end date has already passed (as it's useful for the user to notice that registration has already closed).

**Comment by Leats** [comment]
So far conferences display all scheduled and registered regforms:
https://github.com/indico/indico/blob/549df0cc21659200d2bbd645d45d3e9662d31e7e/indico/modules/events/registration/controllers/display.py#L81

Meetings/Lectures display only open and registered regforms, so no closed ones at all:
https://github.com/indico/indico/blob/549df0cc21659200d2bbd645d45d3e9662d31e7e/indico/modules/events/registration/__init__.py#L79

Maybe it would be better to let them both work in the same way?
Also, reforms, which are scheduled for the future might be interesting to show as well so users know when registration opens?

**Comment by ThiefMaster** [comment]
> Also, regforms, which are scheduled for the future might be interesting to show as well so users know when registration opens?

Makes sense, if a start date is set it's a good idea to show it. AFAIK you can always clear the start/end date in management if you want to unschedule (and thus hide) it.

> Maybe it would be better to let them both work in the same way?

I wonder if we had any reason for having different logic there, but most likely it's just because they weren't written at the same time and/or by different people...

---

Maybe it'd be best to extract the logic of getting the list of registration forms to show in an event into a util function - that way there will be no chance for the logic diverging again in the future. The `user_registrations` structure is slightly different in the two functions, but no reason against just returning the more verbose dict and then either adapting the template or converting to the list of regform ids before passing it to the template.

**Comment by Leats** [comment]
I think it is different because in Meeting/Lecture display the scheduled time for the registration is not displayed, meaning that right now there would still be a button for registering even though registration is not possible):
![Screenshot from 2020-02-18 13-39-13](https://user-images.githubusercontent.com/23189858/74736948-2170ea00-5254-11ea-87a2-2ff8d9d2002f.png)

Suggested solutions:
- Actually don't present non-open/non-registered regforms in meeting/lecture displays (but I can still put the logic into an util function anyway)
- Add a field which informs the user about closing and/or opening date and making the register button non-interactable if registrations aren't open. Not sure about how exactly to display that yet and if there's a pretty way to display it.

**Comment by ThiefMaster** [comment]
I think (2) might be a bit confusing - and scheduled registration openings are not that common anyway. I'd go for (1), create the util function and pass a param (`include_upcoming` or something like that) to specify what you want there
