### ISSUE TITLE
File failed to load: https://indico.fg-aerospace.ch/dist/js/mathjax/extensions/MathZoom.js

### ISSUE THREAD

**Issue by dieperie** [indico/indico#4157]
**Describe the bug**
I freshly installed indico 2.2.4 and wanted to setup a registration form.
I cannot create a form and when exiting is says **File failed to load: https://indico.fg-aerospace.ch/dist/js/mathjax/extensions/MathZoom.js**

**To Reproduce**
1. Go to 'https://indico.fg-aerospace.ch/dist/js/mathjax/extensions/MathZoom.js'

**Comment by ThiefMaster** [comment]
Something is wrong with your config. https://indico.fg-aerospace.ch redirects to https://indico.fg-aerospace.ch:6443/, and https://indico.fg-aerospace.ch:6443/dist/js/mathjax/extensions/MathZoom.js works just fine.

Since this is a config problem, [the forum](https://talk.getindico.io/c/administrators) would be a better place to ask for help.

But here are some pointers:

- check [`BASE_URL`](https://docs.getindico.io/en/latest/config/settings/#base_url) in `indico.conf` - make sure this is set to `https://indico.fg-aerospace.ch`.
- if you are using a reverse proxy in front of indico, [`USE_PROXY`](https://docs.getindico.io/en/latest/config/settings/#USE_PROXY) needs to be set to True and the proxy in front of indico needs to set the appropriate headers
