### ISSUE TITLE
Breadcrumbs in administration pages are not rendered as links

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#4225]
**Describe the bug**
Breadcrumbs segments in category pages in category pages are rendered as links. This is not the case for the breadcrumbs segments rendered in administration pages.

**To Reproduce**
1. Go to 'Home > Administration > General Settings'
2. Notice that breadcrumbs are not links

**Expected behavior**
Breadcrumbs segments in the admin area being clickable like in category pages.

**Comment by ThiefMaster** [comment]
There's no big benefit from having links there since you can get back to the main Administration page via the top meny all the time). And at least the last segment should not be a link since that's the current page - but for the previous one ("Administration") a PR adding the link would be welcome of course :)
