### ISSUE TITLE
Timetable cloning: cloned contributions rendered in different order from original

### ISSUE THREAD

**Issue by maarten-litmaath** [indico/indico#4227]
Dear Indico devs,
as discussed in INC2265965, when an event is cloned, the time table of the clone need _not_ look like an exact clone of the original time table, while there appears to be no good reason for the code to behave that way.

This issue affects clones of non-trivial time tables that do not make use of sessions.  Example:

    https://indico.cern.ch/event/873609/timetable/#20200124

**Comment by pferreir** [comment]
Related internal ticket: `INC2265965`

**Comment by pferreir** [comment]
Screenshots included in SNow ticket, for comparison:

![image](https://user-images.githubusercontent.com/2699/71984136-8f270080-3228-11ea-9098-cce370455a4d.png)

![image](https://user-images.githubusercontent.com/2699/71984141-92ba8780-3228-11ea-8775-70cce25c1dea.png)

**Comment by ThiefMaster** [comment]
I investigated it a bit, and I'm pretty sure this is not fixable without risking to break existing events since the ordering of those columns depends on the dict keys (`c<id>`, `b<id>`, etc.) in the timetable data. We could force an order by `id` or by `start_dt, id`, but this would also risk affecting existing events.

**Comment by pferreir** [comment]
@ThiefMaster in that case, I believe it's not worth fixing it.

**Comment by ThiefMaster** [comment]
That could cause some reordering as well but I think it can't be avoided...

Sorting by `type, start_time, code, friendly_id` would probably make things mostly stable/consistent and remove any dependency on object/dict key order... and it'd let people use contrib codes just like session codes if they *really* want something to affect the columns...

**Comment by maarten-litmaath** [comment]
Hi again,
will you consider improving the functionality at some point,
while keeping backward compatibility,
to try and prevent more such occurrences in the future?

**Comment by pferreir** [comment]
@maarten-litmaath sure, but that would be something for the upcoming rewrite of the conference timetable code (see last line in https://getindico.io/roadmap/). I suggest we mark this ticket as such.

**Comment by maarten-litmaath** [comment]
OK, thanks!  Feel free to close this one already.

**Comment by ThiefMaster** [comment]
I think the problem with trying to keep it "backwards compatible" (assuming you mean no changes to any existing events where it looks correct now) is the fact that it relies on dict key order, which means that the only way to keep backwards compatibility would be implementing a custom sorting function that uses whatever algorithm python uses to determine the order of (unordered) dict keys, and applying this order to the data...

PS: The dict item order will most likely also change once we move to Python 3, and I don't think a specific order is guaranteed in the client side either (since JS objects are always unordered, not like dicts that became ordered in recent Python 3 versions)

**Comment by maarten-litmaath** [comment]
Hi guys,
how about a button that the organizer must click to override the original behavior?
You already have that e.g. for the list of speakers of a contribution...

**Comment by pferreir** [comment]
If we need to go to great lengths to do it perfectly, then it won't be worth it. We could do as @maarten-litmaath suggests and have a "custom order" option which would allow people to organize the timetable as they please (see #2386 for instance). Then we could set all current events to however they are rendered right now.
OTOH, we'd need to see if that option is desirable and feasible from the implementation PoV.

**Comment by ThiefMaster** [comment]
> and feasible from the implementation PoV

I think that's the problem... at least if it's the order on the python side. In case it's the ordering on the JS side causing the problem, we could send it as a list (with consistent order) to the client, and if "legacy mode" is used, run it through something like `Object.values(Object.fromPairs(...))`

**Comment by pferreir** [comment]
> at least if it's the order on the python side.

In that case, can't we just convert it to a list on the Python side and save it in the DB like that?

**Comment by ThiefMaster** [comment]
But then we'd lose the order the items for existing events have, possibly breaking cases like the one from Maarten that rely on the current order

**Comment by pferreir** [comment]
Not sure I understand. What I mean is saving the "current order" as a list for all existing events during the DB migration.

**Comment by ThiefMaster** [comment]
Heh, I thought about this as well and quickly discarded the thought due to how awful it'd be to do that ;)

But after checking again it's luckily only the JS order, which is actually pretty consistent (to my surprise, I'd expected worse from JS 🙈): https://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order

This also means that there is a trivial fix for the cloning inconsistency after all :)
