### ISSUE TITLE
Programme codes: Display speaker information in programme codes assignment window

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#4323]

**Comment by ThiefMaster** [comment]
How is this supposed to work for contributions with TONS of (co-)authors? Do we have any details on the exact usecase for this @meluru?

**Comment by meluru** [comment]
Yes, the use case is as follows: in JACoW on poster sessions programme codes are used as poster board numbers. During the session, the posters are physically placed next to each other in incrementing order by the programme code. In that case when one author has several posters he needs programme codes that are next to each other.
Originally (in SPMS) they have an option to sort contributions before assigning programme codes, but that wouldn't work in our case as the number depends on the contribution id. So the idea was to display authors information in the assignment window so that the manager could adjust programme codes manually. I guess the poster presenter is usually the speaker so showing only speakers could be enough. (maybe it can be rediscussed with JAcoW)

**Comment by ThiefMaster** [comment]
Only speakers sounds like a really good idea to make this not blow up the page!

**Comment by meluru** [comment]
Again, encouraging people to specify thier speakers correctly

**Comment by ThiefMaster** [comment]
Do we only need speaker names there or also their affiliations?
