### ISSUE TITLE
Do not leave dangling comments when undoing the submitter's accept/reject of proposed changes

### ISSUE THREAD

**Issue by pferreir** [indico/indico#4350]
This will allow us to keep the comment tied to the revision, and to make it go away once we "undo" a decision.

**Comment by ThiefMaster** [comment]
After looking at the PR and the code again we do not need to split this column at all, since making changes as a reviewer will always set the comment on the revision that's being reviewed, and then create a new revision with the updated files (which is the one the submitter can accept/reject).

So instead of splitting we should:

- set the comment on the revision when accepting/rejecting proposed changes
- update the UI to ensure this is shown properly (ie not showing the comment on the "Editor has made some changes to the paper" block)
