### ISSUE TITLE
No subcategories without effective_icon still outputs LEGEND in Category views

### ISSUE THREAD

**Issue by marengeti** [indico/indico#4423]
When loading a Category overview page, the left-column includes Calendar, Display Options form and, IF there are sub-cats with effective_icon, a LEGEND section.

According to the template code, the LEGEND section title should not be output when there are no such sub-cats.

The problem seems to be that the subcategories query is passed as a param to the template prior to being evaluated, and the bool test for it will always evaluate to true. A simple fix for this could be:

```
$ git diff indico/modules/categories/controllers/display.py
diff --git a/indico/modules/categories/controllers/display.py b/indico/modules/categories/controllers/display.py
index efedb3905f..22daa76cdf 100644
--- a/indico/modules/categories/controllers/display.py
+++ b/indico/modules/categories/controllers/display.py
@@ -479,7 +479,7 @@ class RHCategoryOverview(RHDisplayCategoryBase):
         params = {
             'detail': self.detail,
             'period': self.period,
-            'subcategories': subcategories,
+            'subcategories': subcategories.all(),
             'start_dt': self.start_dt,
             'end_dt': self.end_dt - relativedelta(days=1),  # Display a close-ended interval
             'previous_day_url': self._other_day_url(self.start_dt - relativedelta(days=1)),
```

**Comment by ThiefMaster** [comment]
Yes, this fix looks good. I'd add the call up here instead since storing a query in a variable not named query is confusing to begin with.

    subcategories = Category.query.filter(Category.id.in_(subcategory_ids)).all()

No need for a PR; I'll push this directly to master.

**Comment by marengeti** [comment]
Yes, I agree. I have noticed some (confusing) instances when a query is passed around looking like data, but it is still a query... it would be good to avoid this categorically, and maybe fix a simple naming guideline to avoid this potential confusion (and bugs!) when reading the code.

**Comment by ThiefMaster** [comment]
If you find more places like this please let us know (or send a PR fixing them, just don't send one PR for each instance of such a naming problem as this would be somewhat noisy to have possibly many one-line-fix PRs - better to just mention it somewhere).

The guideline is basically this: **If a variable isn't named `query` or `something_query` then it should not contain a query object.**

If the query is never need later (ie all that's done is calling `.all()` or iterating it), then the easiest fix is moving the `.all()` to the place where it's being assigned (like in the commit I just pushed); otherwise renaming it is the way to go.
