### ISSUE TITLE
Downloading attachments have wrong filenames (Unicode)

### ISSUE THREAD

**Issue by tomohikosan** [indico/indico#4465]
**Describe the bug**
Files uploaded with the material editor do not preserve their filenames when downloaded, if they include (non-ASCII) unicode characters.

**To Reproduce**
1. Go to 'Material Editor'
2. Upload file with filename (for example) 'TEST日本語123.txt'
3. Go to the event page, right-click and download the file above.
4. The downloaded file has a filename 'TEST123.txt', which is different from the original.

**Expected behavior**
In the example above, the downloaded filename should be 'TEST日本語123.txt' instead of 'TEST123.txt'.

**Screenshots**
Here is a screenshot of how the file looks in the agenda page (it is correct here):

![unicode-filename](https://user-images.githubusercontent.com/4271767/82746001-b4766e80-9dc5-11ea-8839-73856e525630.png)

This shows that, at least in this intermediate step, the filename seems to be properly stored.
However, the actual URL to the file (and therefore how the web browser saves the file) does not have the correct filename.

Here is a screenshot of the web browser pointing to the file:

![unicode-filename2](https://user-images.githubusercontent.com/4271767/82746011-00291800-9dc6-11ea-85c6-dfa71315fd68.png)

**Additional context**
* This behavior was seen at http://indico.cern.ch/
* Uploading seems to be working fine, since the internal representation shows the correct filename.
* It seems the generation of the download link alters the filename.
* It seems the non-ASCII characters get omitted.

**Comment by ThiefMaster** [comment]
We currently strip all non-ascii characters from filenames because back when writing this code a few years ago, browser support for unicode filenames wasn't as good as it is now, so it was the right thing to do.

However, you are right that we should start sending the original filename when downloading a file, and I could have sworn that I created an issue for this a few months ago when implementing this for another case where users can upload files... anyway, now that you created one we have one. :)

**Comment by tomohikosan** [comment]
Thank you very much for the quick response!
