### ISSUE TITLE
Event cloning: Allow cloning into an existing event

### ISSUE THREAD

**Issue by meluru** [indico/indico#4518]
The idea is to extend Event Cloner functionality to cloning into an existing event.

The implementation could allow cloning only modules that are empty in the target event (in order to avoid conflicts or replacing data).

**Comment by ThiefMaster** [comment]
Adding what I mentioned on IRC: I think this would be a very useful feature, but there's a real risk of people breaking events even more than they currently do when accidentally editing the source event instead of the clone. So I think not allowing to use any cloner unless there is no data in the target event (or **only** data that would never conflict in case where we always have some data - e.g. the creator in the ACL) would be a requirement to greatly lower this risk.

We'd also need to decide the UI for this. Would it be something you do in the target event ("Import data from existing event")? Something in the source event ("Clone to existing event event")? I'd probably go for making it something in the target event, where you e.g. paste the URL of the source event to import from (no need to have a fancy search for events you can manage that way).

Implementation-wise, cloners could:

- have a new class attribute indicating whether they support cloning to existing events in general (only if we have cloners we never want to use there)
- have a new instance method that takes the target event and returns whether cloning to that event is possible (there you would check for conflicts)
- maybe have a new flag (either in the constructor or in `run`) indicating whether you are cloning to an existing event - for the case where you need to do some merging or extra checking (e.g. when cloning the event ACL).

---

But first of all let's get some more input from @indico/development-team on this whole idea :)

**Comment by pferreir** [comment]
Related: #2794

**Comment by meluru** [comment]
These all are great tips. 

For the UI: I think the users might confuse "Clone into existing event" with usual "Clone" so I agree, it would be better to add something in the target event. 

As for the URL, it sounds easier to implement, but I'm a bit concerned that someone might copy wrong url and not notice that. I would display basic event data (title, date) after the URL is pasted so that we can avoid mistakes.

**Comment by Leats** [comment]
I agree with implementing it into the target events. That makes it more clear that people add something to exactly that event, not the other way around (also, as @meluru said, no confusion with the already existing cloning)

Asking the user to verify the pasted URL via title and date sounds good to me as well as first step of the cloning.

I'm also for not allowing cloning when there would be conflicts, as long as the user can understand why cloning is not possible. Is that something the user could remedy, then, manually? like, delete the data that's conflicting so they can clone into the event?

**Comment by ThiefMaster** [comment]
:+1: on displaying details about the event - that should make it very clear. We could even do it similar to what we do when merging users: Show clearly what the source and target events are (category, title and dates), and have them confirm the operation since even if it doesn't destroy anything it would be a bit of a mess to accidentally import data from an even you don't want to import.

Yes, for most (all?) conflicts manually deleting the objects should work. We don't enforce e.g. `friendly_id` uniqueness for deleted contributions/registrations.
