### ISSUE TITLE
How to find out who created an event?

### ISSUE THREAD

**Issue by dguest** [indico/indico#4580]
I have access to an indico category which has the "Restricted event creation" option set to off, which is great in that anyone can create events in the category. Unfortunately the category has a number duplicated or abandoned which I can't attribute to anyone. Ideally I'd contact them directly and ask, but I don't see where this information is stored.

Is there some kind of "creator" field for events that don't have any other information?

**Comment by ThiefMaster** [comment]
If you go to the management area of the event, it's shown right below the event title:

![image](https://user-images.githubusercontent.com/179599/89165204-81481c80-d578-11ea-94a4-9d406610b18f.png)

PS: Please do not use this issue tracker for support questions. Besides the more standard support lines such as SNOW and the Indico Mattermost channel in IT-dep (since you appear to be at CERN as well), we also have a community forum where such questions would be fine: https://talk.getindico.io
But the issue tracker is not a good place for it, since having general support question here just adds noise among actual issues and feature requests.
