### ISSUE TITLE
Syntax error in doc generation?

### ISSUE THREAD

**Issue by DirkHoffmann** [indico/indico#4611]
Sorry for my ignorance, but I have no idea how the following line could possibly be legal code in python(3).

https://github.com/indico/indico/blob/b11b9c9c000a8bf8949fa704ee72f45bf17c1900/docs/source/exec_directive.py#L22

I am not alone with my ignorance, `sphinx-build-3` says the same, and when I simply comment this line, it seems that I can generate some useable version of the documentation in HTML. Is there anything wrong with this line, or is it me?

I naively surrounded the argument with paranthesis, and I get my documentation, albeit with a big number of warnings (`No module named 'indico'`).

Is it worth making a PR for this? It seems to me that the generation in doc (`Makefile`, `make.bat`) is not up to date anyway. Maybe part of a bigger task or PR already?

**Comment by ThiefMaster** [comment]
It's valid Python 2 but not valid Python 3, since `exec` became a function there.

It sounds like you are using a globally-installed sphinx-build that's likely using Python 3. Instead, activate the indico virtualenv - if you installed the packages from `requirements.dev.txt` you should have `sphinx-build` installed there.

**Comment by DirkHoffmann** [comment]
Yes, I did not initialise the dev environment for compiling some trivial changes in the doc. :smile: 

I had never realised that `exec` did not need parantheses, because `exec("print 1")` is valid python2 as well. But there is a problem with `cStringIO` in the same file. So, if you want me to submit the updates to a python/indico3 branch, I will do. Otherwise let's close this (and/or keep it in mind for the migration to 3).

**Comment by ThiefMaster** [comment]
No, it's fine for now... let's wait with those things until we move to Python 3.

Most likely already changing syntaxes would work, but at least the Python 2 version coming with CentOS7 does not fully support the new function syntax even though in general Python 2.7 does support it already. I don't remember what exactly the problem was, just that [something didn't work](https://github.com/indico/indico/commit/03f0334aab5) when I attempted it the last time in another file,,,
