### ISSUE TITLE
Incorrect handling of unsupported HTTP methods

### ISSUE THREAD

**Issue by andy-slac** [indico/indico#4643]
**Describe the bug**

When Indico responds to a unsupported HTTP method (e.g. `TRACE` or `TRACK`) it correctly returns status code `405 METHOD NOT ALLOWED` but it also returns a full Indico page in a response body as if `GET` method was used. According to standard `405` response should also include `Allow:` header with the list of supported methods which is missing from Indico response. Standard does not say what should be contained in response body but I believe that body can be empty or contain some error message, but not an Indico page. In a standard setup with Apache (with the same indico.conf as provided in Indico docs) with reverse proxy Apache redirects all request to uwsgi and does not rewrite responses meaning that whatever is generated by Indico is returned to client.

**To Reproduce**

Run `curl` with `TRACE` method for example:

    curl -k -v -X TRACE https://indico.host

or `TRACK`:

    curl -k -v -X TRACK https://indico.cern.ch

**Expected behavior**

Invalid request methods should not return Indico pages.

**Screenshots**

Here is the response packet from tcpdump that was generated by uwsgi in response to TRACE request with curl example above:
```
HTTP/1.1 405 METHOD NOT ALLOWED
Content-Type: text/html; charset=utf-8
Content-Length: 36820
X-Indico-URL: /

<!DOCTYPE html>

<html prefix="og: http://ogp.me/ns#"
      data-static-site="false">
<head>
    <title>*** Indico (Indico)</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="csrf-token" id="csrf-token" content="00000000-0000-0000-0000-000000000000">
    <link rel="shortcut icon" type="image/x-icon" href="/images/indico.ico">

    <meta property="og:image" content="https://******/images/indico_square.png">
    <meta property="og:site_name" content="****** Indico (Indico)">
...
```

**Additional context**

Centos7 with httpd 2.4.6, Indico 2.3, Python 2.7.

**Comment by ThiefMaster** [comment]
This sounds more like a configuration issue with Apache. You should probably configure it to restrict those methods and only allow standard ones (HEAD, GET, POST, PUT, PATCH, DELETE) if you care about this.

In fact, when I send a TRACE request to my instance I get a 405 from nginx, but for TRACK and completely made-up HTTP verbs the request does go to Indico, but Indico responds with the "pretty" 405 page (since it correctly recognizes it as a method that's not allowed):

```html
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>
```

Since not even nginx bothers sending an `Allow` header I think we can live without that. It's not really important for real-world usage anyway...

**Comment by andy-slac** [comment]
Adrian, please do not close the issue if you disagree with something, we need a solution and I think it's helpful to everyone if we can cooperate on finding something that can also be used by other people. 

I'm not sure why you decided that this is not relevant for real-world usage, I can see that CERN Indico is also not handling this correctly and this as real-world as it can be:
```
$ curl -k -v -X TRACK https://indico.cern.ch
*   Trying 2001:1458:d00:9::100:109...
* Connected to indico.cern.ch (2001:1458:d00:9::100:109) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: CN=indico.cern.ch,O=Organisation Européenne pour la Recherche Nucléaire (CERN),STREET=Route de Meyrin 385,L=Meyrin,ST=Genève,postalCode=1217,C=CH
*       start date: Feb 27 00:00:00 2020 GMT
*       expire date: Mar 23 23:59:59 2022 GMT
*       common name: indico.cern.ch
*       issuer: CN=Sectigo RSA Organization Validation Secure Server CA,O=Sectigo Limited,L=Salford,ST=Greater Manchester,C=GB
> TRACK / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: indico.cern.ch
> Accept: */*
>
< HTTP/1.1 405 METHOD NOT ALLOWED
< Server: nginx/1.18.0
< Date: Wed, 30 Sep 2020 15:58:38 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 43802
< X-Indico-URL: /
< Set-Cookie: indico-worker=indico-cern-wk1; path=/; HttpOnly
<
<!DOCTYPE html>

<html prefix="og: http://ogp.me/ns#"
      data-static-site="false">
<head>
    <title>Indico</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="csrf-token" id="csrf-token" content="00000000-0000-0000-0000-000000000000">
    <link rel="shortcut icon" type="image/x-icon" href="/images/indico.ico">

    <meta property="og:image" content="https://indico.cern.ch/images/indico_square.png">
    <meta property="og:site_name" content="Indico">


    <meta property="fb:app_id" content="269567379750914">
...
```
It does not respond with a "pretty" page but with a regular indico page.

For Apache configuration we are using your recipe that you provided to the whole real-world here: https://docs.getindico.io/en/stable/installation/production/centos/apache/#configure-uwsgi-apache. I guess that it indeed does not restrict methods and proxies every non-static request to Indico. I think it would be nice if you updated that recipe with something that makes expected response to non-supported HTTP methods. Unfortunately I'm not an expert in Apache and cannot help much with that, but I will try to experiment with our setup.

Could you please re-open the ticket so that we can track progress here.

**Comment by ThiefMaster** [comment]
For this **exact** `curl` command you posted (just made less noisy, but same type of page with your arguments):

```
[adrian@claptrap:~]> curl -sk -X TRACK https://indico.cern.ch | grep -A1 Method
    <h1>Method Not Allowed</h1>
    <p>The method is not allowed for the requested URL.</p>
```

![image](https://user-images.githubusercontent.com/179599/94716805-b17d2300-034f-11eb-8b8d-449cd5e41695.png)

So as far as I can tell, everything is fine there.

The RFC does not say that sending a pretty-looking page is not OK.

Is the lack of `Allow` header violating the RFC? Yes. Is this a problem? I don't think so - if you have any *real-world* issue with this (beyond "this violates the RFC's "MUST"), please let us know.

FWIW, even the official nginx website (running on nginx) does not include this header:

```
[adrian@claptrap:~]> http -phH trace http://nginx.org/
TRACE / HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 0
Host: nginx.org
User-Agent: HTTPie/2.2.0

HTTP/1.1 405 Not Allowed
Connection: close
Content-Length: 157
Content-Type: text/html; charset=utf-8
Date: Wed, 30 Sep 2020 17:06:42 GMT
Server: nginx/1.19.0
```

Or if I check the Apache running on https://home.cern, it contains an `Allow` header, but with no value - so just as useless as no header altogether, because obviously there *are* some allowed methods (GET):

```
[adrian@claptrap:~]> http -phH trace https://home.cern/
TRACE / HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 0
Host: home.cern
User-Agent: HTTPie/2.2.0

HTTP/1.1 405 Method Not Allowed
Allow:
Content-Length: 222
Content-Type: text/html; charset=iso-8859-1
Date: Wed, 30 Sep 2020 17:07:10 GMT
Server: Apache
Set-Cookie: cerndrupal_prod_https=drupal8p13; path=/; HttpOnly
```

> please do not close the issue if you disagree with something

Closing a ticket does not prevent people from commenting on it or us from reopening it if we realize there is an actual issue. But so far this ticket does not look like something that needs any action from our side.

**Comment by andy-slac** [comment]
Hi Adrian,

my fault, I did not realize (and the people who alerted me to that) that that 40kB HTML page actually contains an error message. I would have expected something smaller, similar to what you showed above from nginx. Is there a good reason to return a huge HTML page with bunch of additional JS scripts linked to a client which is likely not even a browser-based (I don't think regular browsers will ever send a TRACK or TRACE request)?

Regarding `Allowed` header - I think there is a value in following RFC instead of bad practices from random guys. I can probably understand nginx logic because they say it's hard for them to know what `Allowed` should be in generic server setup, but for Indico at application level you should expect to know that information, no? I think these lines: https://github.com/indico/indico/blob/master/indico/web/rh.py#L196-L197 already pack all necessary info into an exception.

It is up to you of course to implement this in a way you decide, my concerns come mostly from the security audits that we have for our installation and people asking all sorts of questions that are not unreasonable.

**Comment by ThiefMaster** [comment]
Those are all the methods Indico considers valid - not necessarily all methods that are allowed for a given endpoint. So including them in the `Allow` header wouldn't be better than not sending it at all.

Including an `Allow` header would be something to be implemented on the [Flask](https://github.com/pallets/flask) or even [werkzeug](https://github.com/pallets/werkzeug) level since it takes care of routing and knows which methods a given path will handle. I think opening an issue there would make a lot of sense!

I'm aware of security scanners being picky about those methods (being also a member of the CERN computer security team I actually told people to configure their webserver to reject those methods), but I would say it is up to the person performing or analyzing any security than to realize that getting an error code + error page rendered by the application is fine (unlike getting a 200 and possibly information that should not be exposed).

> to a client which is likely not even a browser-based (I don't think regular browsers will ever send a TRACK or TRACE request)

We do send errors as JSON in cases where we believe the client expects it. Currently this is the case if the request comes with an application/json content type or the (legacy and non-standard) x-requested-with:xmlhttprequest header.
