### ISSUE TITLE
Update list of titles in Registration Form and disable it by default

### ISSUE THREAD

**Issue by pferreir** [indico/indico#4688]
Actions:
 * There is a gender-neutral non-academic title ("Mx") which seems to be the standard in several official documents and procedures in the UK these days. We have had requests from event organizers to include it in the default list and we believe this would be helpful to others;
 * Titles seem to be losing relevance in daily life. Although useful in some contexts, our experience with the overwhelming majority of Indico events is that only a few people end up filling them in and we almost always end up with a handful of those in a list of mostly "title-less" participants. The idea would be to have the "title" field disabled by default.

This field should remain fully configurable. New titles may be added and the field can even be made mandatory if needed.

**Comment by ThiefMaster** [comment]
We can extend the `UserTitle` with a new option; note that this requires an alembic revision to update some CHECK constraints.

**Comment by kirschen** [comment]
Thanks a lot for picking this up! As a typical Indico user, I would also second dropping the field from the default registration form. For CERN-Indico I would assume that the field often stays empty because the rest of the "Personal Data" is already filled when logged in (First Name/Last Name/Mail/Affiliation), so why bother with filling an optional field. And the title info is usually not useful for anything; so why collect it in the first place (cf. GDPR).

**Comment by ThiefMaster** [comment]
@kirschen this change is now in production on the CERN indico instance
