### ISSUE TITLE
Event cloning: add "update user data" checkbox

### ISSUE THREAD

**Issue by pferreir** [indico/indico#4750]
Scenario:
 * User is added to an event;
 * User updates their profile data (on their profile page);
 * Someone else clones the aforementioned event;
 * Event still contains the old user data.

This is a pretty common source of misunderstandings. I suggest we add an "update user data" checkbox which will tell Indico to fetch the users' latest profile data upon cloning. I would also suggest to have that enabled by default.

**Comment by ThiefMaster** [comment]
Good idea. Since we can't really pass additional options to cloners (the only thing the user can choose is which cloners to run), I think we could work around this by adding another "pseudo cloner" for it which depends on the event persons cloner (and, if we want to wipe out all the override data stored on the person link level, also soft-depends on the contribution, session, etc. cloners) and instead of actually cloning anything just goes over the new event's persons and refreshes the data from the users.

Alternatively, we could make this just a separate option when cloning and then, after running all the cloners, refresh the data.
