### ISSUE TITLE
Introduce use of Roles in Authorized (abstract) Submitters

### ISSUE THREAD

**Issue by t4nec0** [indico/indico#4756]
This request relates in particular when "_Invited contributions_" are in place (ref.: #4042)

For large conferences the Scientific Programme Committee, the body that will create the "draft" (_invited_) abstracts, is quite large. 
Until now the _Abstracts Submission Settings_ allows to **specify a number of Authorized Submitters** (ref.: https://learn.getindico.io/conferences/submitting/) defined as "_These users may always submit abstracts, even outside the regular submission period._" 
I think it is necessary to also **include groups of users** in this specific authorization, and the best concept I can think of is the **Roles** one.

**Comment by ThiefMaster** [comment]
Invited abstracts cannot be created from the end-user-facing submission form - and that's what this setting applies to.

Since managers can create abstracts (both regular and invited ones) at any time from the event's management area, I don't think this is really necessary. However, what would probably make a lot of sense is us adding a new management permission that only grants access to the abstracts parts of event management (like we already have for some other parts)...

**Comment by t4nec0** [comment]
Thanks Adrian, that makes sense of course. 
I'm not sure I get the reason why this "_Authorized Submitter_" feature, already existing and which I propose to "extend" to Roles, is not the best option for you, as I get from your response here.

I tried giving this permission to one non-admin person and he was able to submit an abstract from the end-user-facing screens.

Anyhow you're right in thinking of this feature as an "admin-like" one. Any SPC member needs to "propose" an invited contribution by:

- creating a draft abstract
- assigning this abstract to another "submitter" (the invited person, indeed)
- ask for abstract reviewing by a committee (could be the same SPC or, in principle, a different one - I'm thinking of using the roles concept again here, of course)

Also, I propose to extend the documentation with more details of these features and the meaning of permissions.

For example, it's not clear to me what's the function of the  "give _Submission rights_" ("_Privileges_" white button) in the _Organization > Participant Roles_ screen. It's not so clear if this affect the current selection (filter...) or not.
Shall I open another ticket for this?

**Comment by ThiefMaster** [comment]
> assigning this abstract to another "submitter" (the invited person, indeed)

and this particular point is exactly why this is a management-level feature - regular users should are not allowed to submit abstracts on behalf of someone else

> For example, it's not clear to me what's the function of the "give Submission rights" ("Privileges" white button) in the Organization > Participant Roles screen. It's not so clear if this affect the current selection (filter...) or not.
> Shall I open another ticket for this?

Maybe this issue would fit better in https://github.com/indico/indico-user-docs/ since it seems to be a documentation issue if we do not explain hat submission rights means in this context. But to answer the question, it's about quickly granting those people submission rights on their contributions. It is not related to (submitting) abstracts.

**Comment by t4nec0** [comment]
alright, understood for the first point. Will you put this in a roadmap for a 2.3.X version?

And, about the '_submission_', I guess it's a problem with the term. Now I guess this feature means "**_files_ submission**".
I probably misunderstood it as "_abstracts_ submission", being it in a "Participant Roles" screen, generic, not necessarily tied to any already existing abstract.
Either this could be a request for better wording in that screen or to document it.

**Comment by plourenco** [comment]
Closed by #4834
