### ISSUE TITLE
Insert materials as ATTACH properties in iCalendar export

### ISSUE THREAD

**Issue by dilyanpalauzov** [indico/indico#4794]
I visit https://indico.cern.ch/event/848680/ and then download https://indico.cern.ch/event/848680/event.ics?detail=contributions .  It contains no ATTACHments.

Then I click on https://indico.cern.ch/event/848680/ on “Download material” and the system offers me at https://indico.cern.ch/event/848680/attachments/package to download a file ”material-package.zip”.

Include in the iCalendar export ATTACH;VALUE=URI: property showing the files related to the events.

**Comment by ThiefMaster** [comment]
Material packages may be huge (gigabytes for big events). We will not include those in the ical file... And I'm not sure how useful a link to the material package page would be... after all, how likely is it that someone wants to get a material archive for a whole event based on their calendar entry instead of just going to the event and downloading materials they are interested in?

**Comment by dilyanpalauzov** [comment]
I do not say that the materials for the whole event shall be included as a single file an the ATTACH property.  Many ATTACH properties can be included too with ALTREP parameter, each providing description.

When the users use CUA which ignores the ATTACH property, it is unlikely that the materials will be downloaded from within the CUA.

**Comment by javfg** [comment]
Fetching all the materials' links would incur a heavy cost. To do so, all the contributions of an event have to be traversed for get the link, and permissions have to be checked. The overhead might be too much, specially considering normally users could just go to the event page to get those materials.
