### ISSUE TITLE
Hide non-public events for anonymous users

### ISSUE THREAD

**Issue by dilyanpalauzov** [indico/indico#4800]
I scroll at https://indico.cern.ch/category/0/calendar to 31 July 2020 and open all 114 events.  Then I click on “HIGCC meeting”: https://indico.cern.ch/event/943751/: Access Denied.  It hides even the title of the event, which is visible in the calendar.

Then I click on “UZH meeting”: https://indico.cern.ch/event/866642/: I have to login.

* For unlogged users show by default only events, which unlogged users are entitled to see (anonymous access).

Rationale: to be able to consume the public information, users shall be shown only information, that they are entitled to see.  Otherwise the information is much more than necessary, which hinders its consumption.

**Comment by ThiefMaster** [comment]
While doing this for anonymous users without an account would be feasible (because anything with restrictions could be hidden without any further checks), as soon as someone is logged in, performing access checks on all would be rather expensive (it may involve looking up LDAP group membership etc).

That's why we use the "visibility" setting of categories and events which determine how far up in the chain they are visible in those calendar views.

But all technicalities aside, I do not think it makes much sense to use the calendar view for the root category in any larger Indico instance at all - generally people go to a category containing something they are interested in, and then use the calendar in there.

**Comment by pferreir** [comment]
I agree with @ThiefMaster. This is a NOFIX.
