### ISSUE TITLE
Unrestricted URL redirects

### ISSUE THREAD

**Issue by pingdave** [indico/indico#4814]
Would like to request the ability to limit where the next functionality can redirect a user's browser.  It would be great if we could provide a list of trusted hosts or domains where redirects are enabled
OR
maybe just have the ability to disable next redirects?

For instance, after logging in to an Indico website, this URL:
https://indico.conference.website/login/?next=https://www.google.com
will redirect the user to a Google website or a malicious site where they could prompt the user to login again and then harvest the username and password.

**Comment by ThiefMaster** [comment]
Disabling redirects altogether makes no sense, IMO, but a PR to restrict it to relative URLs or URLs starting with the current `request.url_root` would be appreciated.

For logging in/out this should ideally be fixed in [Flask-Multipass](https://github.com/indico/flask-multipass/blob/master/flask_multipass/core.py#L122); but during signup this is indeed something to fix directly in Indico (`register_next_url`)

**Comment by pingdave** [comment]
I have no problem with only allowing relative redirects, but allowing redirects to other servers seems to be problematic from a security standpoint.

**Comment by ThiefMaster** [comment]
That's what I meant - allowing only redirects within Indico.

**Comment by pingdave** [comment]
Sorry, I don't know enough about the Indico product to suggest how to do it.  Appreciate your help with this.

**Comment by ThiefMaster** [comment]
Fist part of the fix (for the `next` arg during login) is done: indico/flask-multipass#45

The fix in Indico for the signup and logout redirects will come tomorrow (and also a release that includes all those fixes).

**Comment by ThiefMaster** [comment]
Huh, not sure why merging #4815 didn't close this... Anyway, this is fixed and included in v2.3.4
