### ISSUE TITLE
Mandatory fields "Affiliation" and "Comment" in the account request form

### ISSUE THREAD

**Issue by andriish** [indico/indico#4819]
Dear Indico team,

here is a tiny feature request for your consideration.

The problem:

In some cases one needs to enable a registration
for extrnal users. The users, however, too often ignore the fields
"Affiliation" and "Comment" even if they are explicitely asked to fill
them. This creates a situation when the only known information about
the user is the e-mail/name. It hard to decide based on that
information only if one should accept/reject the requst, especially in
the cases when the e-mail adress is from a commercial site.

Possible solution:

Mandaratory fields "Affiliation" and "Comment" in the account request
form would help to get more information for the decision making.

Alternatives:

The solution above + make it possible for indico admins to select if these fields are mandatory

![example](https://user-images.githubusercontent.com/7208673/111070797-994f2980-84d3-11eb-9fde-024d4539ff25.png)

Bet regards,

Andrii

**Comment by ThiefMaster** [comment]
This would absolutely need to be configurable.

**Comment by Naveenaidu** [comment]
@ThiefMaster  This feature request looks interesting, I would like to take it up to get myself acquainted with the code base.

I had few questions regarding this which  could help me get a better understanding ^^' :

1. When @andriish mentioned about `enable a registration for external users`. I wanted to confirm that external users could only register when the `Public Registration` option is selected for an Event in the `Protection Tab` right?

But oddly enough, even when I deselect the `Public Registration` option and tried to access the event using the event url from an `Private/Incognito Tab` I was stil able to get to the login page where I was give the option to create a new account. I thought, if the `Public Registration` was not selected then any user with the url to the event should not be taken to the login page. They should just be barred with a access denied page right? I might be totally wrong here, Please do correct me if I'm wrong. 

-------

When we say that we want `Affiliation` and `Comment` Field as configurable. I had the following questions:

1. Where do we want this configuration to be? 

Do we want this to be a global configuration - I mean something under the `Administration` Tab which an admin can set for all events.

OR

Do we want this option displayed at the `Create Event` Page. Where the creator of an event can select what fields are mandatoory.

IIUC the global option is not what we want right? Because it does not make sense to have a gloabl option of what fields should be mandatory for all events. As this might cause problems when the admin might wanna create event with more liberal constraints. I guess it's better if we have a default option of having those fields as optional and then give the option to the admin when they create event if they want to make any fields mandatory.

2. How should this option be displayed. Is something like below okay:
```
Mandatory fields: [ ] Affiliation [ ] Comments
```

The `square` brackets above are checkboxes.

**Comment by ThiefMaster** [comment]
This whole feature has nothing to do with the registration for an event - it's about registering an Indico account. Moderation is enabled by setting `LOCAL_MODERATION = True` in `indico.conf`.

I would add a new setting with two checkboxes (we already have a wtforms field for this - `IndicoSelectMultipleCheckboxField`) to the "User settings" dialog on this page (but hide them if LOCAL_MODERATION isn't enabled):

![image](https://user-images.githubusercontent.com/179599/123793092-a278d080-d8e1-11eb-86ce-389242708e39.png)

**Comment by elsbethe** [comment]
I came across this issue and since the last update is almost a year ago I was wondering if it's okay that I start working on this issue to get to know the codebase of Indico.
