### ISSUE TITLE
Fix minor UI issues

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#4821]
- [ ] Participant roles: Horizontal scrollbar as soon as there's a vertical scroll bar:

![image](https://user-images.githubusercontent.com/179599/111162014-03cb9c80-859c-11eb-9170-724d86db98af.png)

---

- [x] List of registration forms (and probably similar places): Label with count is way too high

![image](https://user-images.githubusercontent.com/179599/111162086-1a71f380-859c-11eb-8475-c46aa6497fbe.png)

---

- [x] Contact Paper Peer Reviewing team: "Show" label loses boldness on hover

![image](https://user-images.githubusercontent.com/179599/111172218-ebf91600-85a5-11eb-875c-1c190c1739ef.png) ![image](https://user-images.githubusercontent.com/179599/111172177-e4397180-85a5-11eb-95d0-fc80b95867a7.png)

**Comment by ThiefMaster** [comment]
Two issues fixed, the other seems to be a bug in the latest Firefox (87.0).

**Comment by ThiefMaster** [comment]
Reopening since the scrollbar issue doesn't seem to be a browser problem in the end: https://stackoverflow.com/a/66661181/298479

**Comment by javfg** [comment]
After a lot of research, this is what I have found so far:

The problem is a difference in behavior between Chrome and Firefox, which is reported as a Firefox bug: [764076](https://bugzilla.mozilla.org/show_bug.cgi?id=764076). Although it looks like Firefox seems to be more in line with the [CSS specification](https://drafts.csswg.org/css2/#overflow),

> In the case of a scrollbar being placed on an edge of the element’s box, it should be inserted between the inner border edge and the outer padding edge. Any space taken up by the scrollbars should be taken out of (subtracted from the dimensions of) the containing block formed by the element with the scrollbars.

even [Firefox devs agree](https://bugzilla.mozilla.org/show_bug.cgi?id=764076#c7) that Chrome seems to be doing something closer to what would be expected (at least in this case).

The result in our dropdown looks good in Chrome:

![image](https://user-images.githubusercontent.com/6058151/113863127-93cec180-97a9-11eb-98b2-83af086f45b9.png)![image](https://user-images.githubusercontent.com/6058151/113863636-338c4f80-97aa-11eb-86fc-14c3ff32cb45.png)

But will display a horizontal scrollbar in Firefox, as the vertical one takes up space needed to fully fit the widest `li` in the `ul`:

![image](https://user-images.githubusercontent.com/6058151/113863832-6e8e8300-97aa-11eb-8708-0c31139b7bad.png)![image](https://user-images.githubusercontent.com/6058151/113863965-9bdb3100-97aa-11eb-89be-d79b889b96db.png)

As mentioned by [the stackoverflow answer](https://stackoverflow.com/questions/66660266/why-does-firefox-add-horizontal-scroll-bars-once-vertical-ones-are-needed/66661181#66661181). But contrary to what he assumes, Chrome is indeed resizing the element in order to accomodate the scrollbar. It starts at 188.19px width —just like in Firefox— and ends up being 198.19px in my system:

https://user-images.githubusercontent.com/6058151/113864886-ba8df780-97ab-11eb-9344-03222a083fe7.mp4

So although it is not strictly a bug, it is an inconsistent behavior and might eventually be changed in Firefox. Regardless, the bug report is open since 2008, so we should not hold tight.

Meanwhile, if we add some padding with the mozilla-specific `-moz-padding-end` property to the `li` elements, the problem is solved in the least disruptive way, as it only modifies the look in Firefox:

![image](https://user-images.githubusercontent.com/6058151/113866068-27ee5800-97ad-11eb-8636-25577d06665c.png)
