### ISSUE TITLE
Generic way to mark/filter registrations

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#4948]
Sometimes event organizers want to filter registrations based on some custom status and keep this persistent (e.g. to indicate who they already contacted about something etc)

Indico v1 had "custom statuses" which could do that. We replaced them with "management-only sections", but those are somewhat cumbersome to use: You need to edit the registration which is not only a heavy process and not something that can be done in bulk (and it also implies filling any mandatory fields added since the user registered).

Some possible solutions for this:

- bring back custom statuses; basically tags with a name and a color
- just add predefined flags with a color (like the color labels in lightroom). they wouldn't have a name/title, the interpretation would be completely up to what the event organizers decide outside indico

Regardless of the solution, assignment would be done either on the management display page of a registration or in bulk in the registration list. Of course it should also be possible to filter the registration list based on the flags

**Comment by SebastianLopienski** [comment]
@ThiefMaster 's problem statement and possible solutions are spot on.  

Just to add a few additional comments, from the event organizer's point of view:

* I'd preferred the custom statuses or flags to be named - in order to avoid confusion between co-organizers of the same event
* Ideally, I would need to define my custom statuses/flags in a separate place (same way as I manage contribution types); rather than declaring them live, when assigning those statuses/flags to certain people (as, for example, contribution keywords). The latter approach is more prone to errors, typos etc. - for example, we would risk ending up with some registrations marked as "invited" and others "intived"...
* It's crucial to be able to assign, or remove(!) these statuses/flags in bulk - the same way I can now select multiple  registrations, and then "Approve" them in one click
* Finally, just to confirm - for this feature to be any useful, it must be possible to filter the registrations by these statuses/flags
* And obviously, adding or removing these statuses/flags should be transparent for the registered people, and should not trigger any e-mail to them.

Thanks in advance, really looking forward to having this feature implemented!

**Comment by ThiefMaster** [comment]
> Ideally, I would need to define my custom statuses/flags in a separate place (

yes, absolutely. i don't like auto-create when it comes to tagging etc either - you usually end up with typos/duplicates ;)
