### ISSUE TITLE
Allow displaying all events descending from a category

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#4982]
In the category display view, rather than listing only the events that are directly linked to the category, it could be possible to list all the events descending to the category (i.e. events linked to subcategories).

This is a feature that was implemented on the UN plugin via monkeypatching. As we are consolidating the plugin's codebase and and relying more on signals it's becoming clear: 1) that this feature requires a non-negligible number of signals to be properly implemented on the plugin side and 2) that this feature is of general usefulness to all Indico instances.

## UI proposal

The flat list of events could be triggered by:
- URL parameter (e.g. `?flat=1`, `?deep=1`)
- Link under the `View` button (eye) in category pages (e.g. `All descending events`).

|view|trigger|
|:-|:-|
|![image](https://user-images.githubusercontent.com/716307/124125250-adfeff80-da79-11eb-8352-3ae71113f757.png)|![image](https://user-images.githubusercontent.com/716307/124122707-b43fac80-da76-11eb-93db-9316b9b63e3b.png)|

## Performance considerations

- The implementation relies on `Category.deep_children_query` to fetch all subcategories. Is this something that may cause problems when done from the Home category, for instance?
- In large Indico instances, displaying ALL the current events descending from the Home category can produce an awfully long list. Is this something that should be limited to X number of events? Could adding some form of pagination (besides showing past and future events) relieve the strain client-side?

**Comment by ThiefMaster** [comment]
> The implementation relies on Category.deep_children_query to fetch all subcategories. Is this something that may cause problems when done from the Home category, for instance?

You can filter using `Event.category_chain_overlaps()`; no need to get the individual subcategories.

> In large Indico instances, displaying ALL the current events descending from the Home category can produce an awfully long list. Is this something that should be limited to X number of events? Could adding some form of pagination (besides showing past and future events) relieve the strain client-side?

This is indeed the main problem with this a feature - I don't have a good idea so let's see if anyone else does (pinging @indico/development-team). Worst case would be an `indico.conf` option to disable this feature on larger instances. Or maybe only allowing it if there are max n levels of nesting below the category? Or max n events in there?

**Comment by ThiefMaster** [comment]
For the sake of large instances I gave it a try on my dev instance w/ hundred thousands of events, and the performance was actually much better than I feared: `[14 queries (0.578003s) | 3.021247s]`

Another concern is that we do not perform access checks on individual events in the event list; by not having access to a category you simply cannot get its event list. However, the "overview" and "calendar" views of categories also descend into subcategories, and just rely on the "Visibility" setting of categories/events to avoid showing events from too deep in the tree in places where they shouldn't be.

However, I have the feeling people usually don't really configure the visibility properly... I'm pretty sure many categories use the default "everywhere" not realizing that this exposes event titles even though their categories are otherwise protected.

**Comment by plourenco** [comment]
I would still be reluctant about just leaving the performance up to the backend. Even though pagination doesn't sound like a bad idea, I'm wondering how well would something like a lazy-loaded list that yielded per X times as big as the window we would want to have and loaded more on scroll look like?

**Comment by OmeGak** [comment]
As per @ThiefMaster's suggestion, I added in the PR (#4983) a `Category.is_flat_view_enabled` setting that is `False` by default. This solves all performance concerns for big instances and allows smaller instances to have it enabled by default in all categories via plugin.
