### ISSUE TITLE
Protected Event Registration Details for non-Indico accounts.

### ISSUE THREAD

**Issue by vasantvohra** [indico/indico#4991]
**Bug Description**
When an event is protected and registration is added by the event manager as a new Indico user(registration) without an Indico account. Then, It is not possible to preview the registration details with [link having token](https://sandbox.getindico.io/event/1913/registrations/698/?token=f9393360-6d09-4f7c-b76e-8d39022612eb) sent via email.

**How to Reproduce**
1. Create a new conference in any category,
2. From protection make the event 'Protected' (protection mode),
3. Create a new registration form,
4. Go to the [registration list](https://sandbox.getindico.io/event/1913/manage/registration/698/registrations/),
Then, ➕ Register ➡️ New User ➡️ Fill the form with an email that doesn't have an Indico account ➡️ Send Email - True
5. Check Email ➡️ click on the link present in 'manage my registration'. Indico will redirect to the login page.

**Expected behavior**
Registration detail should be displayed from the registration link with a token (URL) irrespective of an event is protected or If the event is protected it shouldn't be possible to register someone without an Indico user account?

**Comment by vasantvohra** [comment]
I'm available on Indico matrix via Elements feel free to get in touch if doubts. 
Thanks,
Vasant Vohra

**Comment by ThiefMaster** [comment]
Sounds indeed worth fixing as long as you just want to grant access to the registration-specific pages using the token.

I think the best solution would be to set a variable in `RHRegistrationFormRegistrationBase._process_args` when a valid registration token is used, and override `_check_access` in there to only call the superclass' method if no registration token has been used.

Do you want to send a PR (against master, since this is a very minor bug and we don't plan to make a new 2.3.x release)?

**Comment by vasantvohra** [comment]
yes sure, I'll send a PR.
