### ISSUE TITLE
RegistrationForm `notification_sender_address` settings

### ISSUE THREAD

**Issue by vasantvohra** [indico/indico#4992]
**Describe the bug**
The `notification_sender_address` field description is ambiguous in regards to the `RegistrationForm.sender_address`.

**To Reproduce**
1. Create a new event, enter the contact email in settings.
2. Create a new registration form, keeping the notification sender address empty.
3. Do some actions which trigger an automated notification email.
4. The email received has a from address from the event's contact email not the `config.no_reply` email.

**Screenshots**
## Event settings `contact email`
![image](https://user-images.githubusercontent.com/20479333/124594628-a8d8f080-de7d-11eb-9b06-4e349159cc7a.png)

## Registration form settings `notification_sender_address`
![image](https://user-images.githubusercontent.com/20479333/124594130-0fa9da00-de7d-11eb-827f-3de7ee2b7693.png)

## Email notification
![image](https://user-images.githubusercontent.com/20479333/124594517-81822380-de7d-11eb-832d-cdccc658dfa8.png)

**Additional context**
We fixed it in the UN plugin by just overriding the property and returning `self.notification_sender_address`, if it is `None`, the `make_email` automatically takes `config.no_reply`.
The UN doesn't want to use the contact emails for the automated notification emails.

**Comment by vasantvohra** [comment]
@ThiefMaster Let me know, how you would like this to be resolved? I can open PR for this one too.
Thanks

**Comment by ThiefMaster** [comment]
I see 3 possible solutions here:

- dynamically set the description of the field to use the contact address
- never use the contact address implicitly, ie always use noreply if there's no emailaddress set
- add a new event-level setting to set the default sender address for all outgoing emails within that event

I think the second one is the best "easy" fix, since depending on the setup the indico server may not even be authorized to send emails using the contact address...

The third option would be a bit more complex but be explicit, and the default (not set) would be identical to option 2...

**Comment by vasantvohra** [comment]
Perfect, I'll go with option 2 like
```python
@property
    def sender_address(self):
        return self.notification_sender_address
```
If someone wants to use the contact email, they can copy-paste in the registration form settings as well.
