### ISSUE TITLE
[Feature] Allow to remove placeholders from `room_name_format`

### ISSUE THREAD

**Issue by olifre** [indico/indico#5227]
**Is your feature request related to a problem? Please describe.**
It is currently not possible to remove individual placeholders from `room_name_format`. For example, for some organizations, it might be useful to drop the `{floor}` in case the `{number}` pattern already holds the floor due to a consistent room naming scheme. 

**Describe the solution you'd like**
Possibility to remove individual placeholders from `room_name_format`. 

**Additional context**
Currently, the `input` field shows a `Missing placeholder(s)` message if not all placeholders are used:
https://github.com/indico/indico/blob/5c9fb38207175932a3c285796ca3b82ef0ff56bf/indico/modules/rb/client/js/modules/admin/SettingsPage.jsx#L141-L142

**Comment by ThiefMaster** [comment]
I wonder if we should even make these fields required for all rooms at all then (currently they are). The cleanest option would probably to configure on the Location level which of these fields are enabled/required for a Room in that Location (especially important in case room managers who aren't admins can edit their rooms). Or maybe simply check which placeholders are used and make those fields required (since it'd be very ugly to have an empty value for any placeholder there)

Example:

- `{building}-{number}` placeholder: Building + Number are required for all the rooms, Floor would remain optional
- `{number}` placeholder: Only number required, the rest optional

I would always require at least the number placeholder since building+floor are not reasonably unique.

**Comment by olifre** [comment]
I fully agree, that seems very reasonable. Requiring the `{number}` placeholder for all cases seems very sensible, and for all other placeholders (including e.g. `{site}` ) the !requiredness" could be location-aware.
