### ISSUE TITLE
Registration modification/renewal: add an option to generate an email to the event owners/registration managers

### ISSUE THREAD

**Issue by jouvin** [indico/indico#5265]
As explained in #5264, in some particular cases it is important that any registration modification doesn't stay unnoticed. The original issue was proposing to add a moderated modification/removal similar to the moderated registration but it is potentially complex. As a firt step, and may be as a replacement, it would be nice to be able to (optionally) send an email to the event registration managers when a registration is changed, with the modification details.

**Comment by tomasr8** [comment]
Hello @jouvin
I'm working on this issue and would like your feedback before we move on with implementing this.
My idea is to modify the notification emails so that they clearly show which fields have changed while
still showing you all the fields for context. This is an example of how it could look like.
Values marked in yellow are the new modified values, while the rest is unchanged:
![image](https://user-images.githubusercontent.com/8739637/156200686-d6557a73-23a7-42dc-80a9-b8dac6e3654e.png)

Let me know if this would be helpful to you.

**Comment by jouvin** [comment]
@tomasr8 thanks for taking care of this issue! I think your proposal is nice but I was wondering if it is a mail only received by the registrant or also by the registration managers for the event. My request was mainly about notification of registration managers but I think it is good if the registrant also received a message showing explicitely what he/she changed.

**Comment by ThiefMaster** [comment]
![image](https://user-images.githubusercontent.com/179599/156210026-6d942691-211b-4cf8-a5ed-8523044e647a.png)

This includes modification notifications. I had also completely forgotten about this ;)

**Comment by jouvin** [comment]
@ThiefMaster not sure I interpret properly your message. Do you confirm that the mail proposed is also received by registration managers (if the pref you mentioned is enabled).

**Comment by jouvin** [comment]
OK. I didn't check either recently and I am rarely involved in managing event registrations! It would be good if this email to registration managers could also contain the diff, I think it is the core of the request by the users I mentioned: identify quicly and without  too much risk of missing something what has been changed by the user.

**Comment by ThiefMaster** [comment]
Yes, that's the idea, changing both emails (same template anyway, just different recipients).
