### ISSUE TITLE
Add alerts to exported calendars

### ISSUE THREAD

**Issue by PerilousApricot** [indico/indico#5318]
**Is your feature request related to a problem? Please describe.**
I follow a couple of different sub-groups' meeting schedule by subscribing to their iCal links using my calendaring software. However, the exported links do not have reminders attached to the events, and I often forget to attend meetings.

**Describe the solution you'd like**
It would be nice to have either a per-user or per-link ability to attach default notifications to events. For example, I could say "for any calendar I export, please attach an to the iCal export an alert 15 minutes before and 5 minutes before the event begins". Then my calendar software (Apple calendars in my case" will send me a reminder notification.

**Describe alternatives you've considered**
From my research, it appears that neither Apple calendars nor the iCal format itself support doing this from the client side, so as far as I understand it, this needs to be implemented on the server side.

**Additional context**
I am using the Indico instance at CERN, so it's possible they are using an older version without this software included.

**Comment by ThiefMaster** [comment]
I think multiple reminders would be overkill, but if someone contributed an option (with nice UI of course) to configure whether to enable reminders when generating the ical link, we'd be very likely to integrate it.

> so it's possible they are using an older version

No. In fact we are usually using a newer version than anyone else else ;)

**Comment by PerilousApricot** [comment]
@ThiefMaster Im unfamiliar with the indico code base, but could take at least an initial stab at it. I think it may be easier (code-wise) to apply the setting per-user and not per exported ical. What do you think?

**Comment by ThiefMaster** [comment]
Per user is a good idea and it'd be indeed easier!

If you'd like to give it a shot, here are some pointers:

- The ical files for events/categories are generated though `RHExportEventICAL` and `RHExportCategoryICAL`; in the end `events_to_ical` is used to generate the ical data so that'd be the place to add the alarms - note that `user` can be None if these files are not generated within the context of a specific user
- The user preferences form is handled through `RHUserPreferences` - there's already generic logic for the storage; `UserPreferencesForm` and `user_settings = UserSettingsProxy(....` are the places to add a new setting

The most flexible implementation for the setting would probably be a number field with empty being no reminder, and otherwise the entered value being the minutes before the event when the reminder should be triggered

**Comment by PerilousApricot** [comment]
Hi @ThiefMaster - Please check #5320 and tell me what you think. I was able to test it locally, but I'm unsure of how to write unit tests for this.
