### ISSUE TITLE
`db.DateTime` or `UTCDateTime` column in DB

### ISSUE THREAD

**Issue by vasantvohra** [indico/indico#5596]
## Context
We have mix of `db.DateTime` or `UTCDateTime` columns in Indico DB models, most of them are `UTCDateTime`.
I believe all the date times in the Database should be in `UTC` timezone, `db.DateTime` allows the date time to be naive without specifying the timezone. Whereas, the `UTCDateTime` validates and stores the date time localised in `UTC`.

<hr>

The questions here are as follows -
1. The CORE (CERN) does have `db.DateTime`, therefore do we need to store the time in other timezones in Database? any specific use case?
2. Do we need to specify the timezone in Database, why not directly store the naive date time (without specifying the UTC) and make sure the timezone in DB is always `UTC`?
3. Does storing the specific timezone like `UTC` takes additional storage in the database?
4. Can we be consistent and use one type of DB column for all the DB Models?

The questions arises from this commit, 
- https://github.com/UNOG-Indico/indico-un/pull/1143

## Bug

1. `dt` is a naive datetime, (`request.time`)
2. `format_pretty_datetime(dt, tzinfo=flask.session.tzinfo)`
3. `format_datetime(dt, timezone=flask.session.tzinfo)`

The 2 and 3 gives a different time, `format_datetime` gives the correct time.
And, to get the correct time from the `format_pretty_datetime`, the dt has to be first localised like `pytz.utc.localize(dt)`

**Comment by ThiefMaster** [comment]
- `db.DateTime` is only used in the room booking modules because Room booking does not use timezones on purpose - any times there are assumed to be in the timezone where the physical room is located.

**Comment by vasantvohra** [comment]
Thank you @ThiefMaster for a very prompt answer 👍

**Comment by giusedb** [comment]
> db.DateTime is only used in the room booking modules because Room booking does not use timezones on purpose - any times there are assumed to be in the timezone where the physical room is located.

This also applies to events, since every event is in a physical location, thus the timezone can be inherited, although the participant may be coming from a place with a different timezone.
I think that generally, the best approach is to make a distinction between the storage and the representation. Store the DateTime always with the same timezone definition in the DB(and UTC would be preferable), then scope the time rendering on the templates dependently from the view to render, which might be event-specific, location-specific, user-preference or browser settings.
This way the application can always internally make every comparison smoothly and at the same time, the screen presents date and time consistently with the user-chosen/screen criteria.

**Comment by ThiefMaster** [comment]
That's what we do outside room booking.

And let me explain why in room booking - where we are not timezone-aware on purpose - that would not work well: When you store a a *datetime* with a timezone, let's say UTC, then it's **impossible** to derive the *date* from it without specifying a timezone. For example, 23:30Z is a different date in UTC and UTC+1! So any logic that works on dates / calendar days (which is the case in room booking) will need to know a timezone.

**Comment by giusedb** [comment]
Clear. From your description, it looks like the timezone should be an attribute of the `Location` rather than the time itself, so that you may have the `Location.local_date` property, which gives you the _per-location_ localized date to be used for any dates/calendar logic and keep the _booking time_ to be comparable with any other time in the whole application regardless of the timezone where it is.
something like:

```Python
    @property
    def local_date(self):
        return self.start_date.astimezone(self.location.timezone).date()
```
