### ISSUE TITLE
Add controls to select/clear all items in the category calendar legend

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#6148]
### Is your feature request related to a problem? 
It is cumbersome to filter events from a single item when the category calendar legend contains many items.

### Describe the solution you'd like
Adding `select all` / `clear all` controls in the legend would help switch quickly between filtering all and filtering no events. This will then allow the user to easily filtering events from one or few items in the legend.

### Describe alternatives you've considered
UX considerations for #6149 may inspire us to find different forms of `select all` / `clear all` controls.

### Additional context
This feature request comes inspired by [Perimeter Institute](https://perimeterinstitute.ca/)'s in-house developed calendar view:

<img width="1261" alt="image" src="https://github.com/indico/indico/assets/716307/7b348d86-7739-4df5-812a-a1a9fe9b817c">

---

/cc @dwindibank

**Comment by ThiefMaster** [comment]
You could also see if a SUI `Checkbox` with the indeterminate state (if not everything/nothing is selected) does the job. But maybe the text link isn't a bad idea either...

**Comment by OmeGak** [comment]
That's exactly something I'm prosposing in #6149.

**Comment by dwindibank** [comment]
As an FYI ... the "Reset" in the our old custom calendar, reset the checkboxes to match the "default" for the current URL ... there were some event types that were off by default (that doesn't apply to Indico) ... and it would reset the filters to match the query string (so that we could construct links to certain views). 

I don't think "Reset" is necessary any more in Indico ... but the "Clear | Select All", would still be useful.
