### ISSUE TITLE
RFE - more flexibility in event titles

### ISSUE THREAD

**Issue by maarten-litmaath** [indico/indico#6216]
I would appreciate having more flexibility in event titles to allow them to **stand out** in a category:
* color palette
* bold face
* italics
* more choices for labels, ideally with fully customizable texts.

Thanks for considering these enhancements!

**Comment by ThiefMaster** [comment]
Colors/Markup: Sorry, but this is not going to happen. I'm sure you know what people do when they can freely apply formatting etc. - you quickly get an inconsistent mess, and with coloring now you even have something where any future redesign would have to consider arbitrary colors (or at least arbitrary dark colors, making e.g. a dark mode even harder to provide) ;)

Custom labels: Completely unrelated top the rest of your suggestion, but the idea is that there are a few common labels defined by the admin of an Indico instance - that way they act nicely as metadata. As soon as you allow freetext, it's no longer useful metadata because you have a mess of thousands of people putting slightly different things. If you have a good suggestion for a label on "our" instance don't hesitate to open a ticket (or ping us on Mattermost) to suggest it. If it's something globally useful, we might add it!

Closing this as wontfix for the reason above, plus the fact that you basically the first person asking for this in almost 10 years (maybe I don't remember some others but it'd *still* be a low single-digit number).

PS: We allowed HTML in event titles back in the ancient eras of Indico v1 - and it was a complete mess to clean up when migrating to our current, way more modern, stack! Back when we stopped supporting HTML there (around 2015 IIRC) we simply stopped rendering HTML in event titles (I think in some places we still strip tags instead of escaping them because of some legacy events), and - after fixing a few recent (back then) events manually - we got pretty much zero complaints about people no longer being able to use HTML in there.
